### ISSUE TITLE
Organise a server

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#1]
Now that we are starting to see data in the site it would be really useful to have the server available so we can all see the progress.

**Comment by grahamc** [comment]
It seems it is a fairly cut-n-dry rails application, would something like Heroku's free tier not handle it ok, with the advantage of having less long-term maintenance?

**Comment by henare** [comment]
@grahamc Yes, that's one of the options we've considered and less long-term maintenance is a massive plus.

We've estimated there's probably a similar amount of work to make the application run on Heroku as there is preparing Ansible to build a server (#2). It's really up to OPORA & the project team to decide what they'd prefer.

There's a chance that the database wouldn't fit in Heroku's free tier. Australia's TVFY certainly wouldn't but it does have almost 10 years of data, vs. < 1 year of data so maybe we'd be fine.

**Comment by henare** [comment]
A shiny new Linode has been provisioned for us, yay! :sparkles: 

I did look into Heroku more. We definitely wouldn't have fit the database onto the free tier. It seems like we could have got a MySQL database for about $10/month.

We'd also have to add memcached and elasticsearch and these seem to be around $10/month for basic plans too. So that would've taken us to $30/month already - more than what a Linode must cost us (albeit without the administration overhead, of course).
