### ISSUE TITLE
Translate votes pagination links "first" and "last"

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#101]
See the bottom of [the votes page](https://tvfy-ukraine.oaf.org.au/divisions/rada/2014-11-27/20)

![screen shot 2015-11-17 at 5 39 20 pm](https://cloud.githubusercontent.com/assets/1239550/11204463/2f35aeac-8d53-11e5-9f6a-58ac85b3061e.png)

It's currently:

« First ‹ попередня 1 2 3 4 5 наступна › Last »

**Comment by lisoffsky** [comment]
here you go
First - Перша
Last - Остання
