### ISSUE TITLE
Translate about page header

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#113]
Most of the about page was translated in #86 but we still need the header:

![selection_001](https://cloud.githubusercontent.com/assets/48945/11355254/afd062ec-92a7-11e5-99a8-71eba0e2e5cd.png)

**Comment by orybiy** [comment]
Про проект
Забудь, що _говорять_ політики. По-справжньому важать лише _їхні дії_. Слідкуй за тим, як депутати _голосують_ і дізнавайся про їхню справжню позицію щодо питань, які впливають на нас усіх.
