### ISSUE TITLE
Translate contact section of about page

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#114]
Most of the page was translated in #86 but we still need the contact section:

https://tvfy-ukraine.oaf.org.au/about#contact

**Comment by orybiy** [comment]
Contact - Контакти
Email us at info@opora.org.ua. - Пиши нам на скриньку info@opora.org.ua

You can also read the OpenAustralia Foundation Blog, follow us on Twitter and contribute to our work on Github. - Більше інформації про парламент та моніторингові інструменти ОПОРИ Ти знайдеш на rada.oporaua.org.
