### ISSUE TITLE
Revise thanks section

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#115]
In #86 the thanks/credits section was translated to:

> Портал “<%= inline_project_name %>” був розроблений [OpenAustralia Foundation](https://www.openaustraliafoundation.org.au), незалежною позапартійною неприбутковою організацією. Він заснований на новаторській платформі британського сайту [UK Public Whip site](http://www.publicwhip.org.uk/), створеного Френсісом Ірвінгом і Джуліан Тодд у 2003 році. Велика подяка [Google Australia](http://www.google.com.au), [National Democratic Institute (NDI)](https://www.ndi.org/),  чиї пожертви зробили можливим розвиток цього проекту.
> 
> “<%= inline_project_name %>” був  створений партнерамиГромадської мережі ОПОРА Henare Degan, Matthew Landauer, Luke Bacon, Katherine Szuminska за координації та консультацій Mario Mitre та Jean-Noé Landry. Адаптація сайту до українського контексту та його переклад з англійської здійснений Юрієм Лісовським та Оленою Рибій.

I've got a few suggestions/questions:
- The text mentions Google Australia. While they provided a donation to the Australian project they didn't fund this project. I suggest removing this reference.
- It appears most peoples' names have been transliterated, except for Julian & Francis'. Is this correct?
- The text doesn't link to theyvoteforyou.org.au. I think it should say that this site is based on They Vote For You. Maybe it could say something like, "This project is based on [They Vote For You](https://theyvoteforyou.org.au), which is in turn based on [Public Whip](http://www.publicwhip.org.uk/)"?

Thoughts @lisoffsky, @mmitre, @orybiy?

**Comment by orybiy** [comment]
Портал “<%= inline_project_name %>” був розроблений [OpenAustralia Foundation], незалежною позапартійною неприбутковою організацією. Цей портал базується на ідеї та платформі австралійського проекту [They Vote For You], який, у свою чергу, створений на основі британського сайту [UK Public Whip site](започаткований Francis Irving та Julian Todd  у 2003 році). Велика подяка [National Democratic Institute (NDI)], чиї пожертви зробили можливим розвиток української версії цього міжнародного проекту.
“<%= inline_project_name %>” був створений партнерами Громадської мережі ОПОРА Henare Degan, Matthew Landauer, Luke Bacon, Katherine Szuminska за координації та консультацій Mario Mitre та Jean-Noé Landry. Адаптація сайту до українського контексту та його переклад з англійської здійснений Юрієм Лісовським та Оленою Рибій.
