### ISSUE TITLE
Translate division history notice

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#117]
When a division (vote) is edited we show a notice [like this](https://tvfy-ukraine.oaf.org.au/divisions/rada/2014-11-27/20) at the top of the page:

> Division last edited 11 дня тому by equivalentideas

So we need a translation for:

> Division last edited #{time} by #{person}

and the tooltip:

> View the edit history of this division.

Very similar to #66.

**Comment by orybiy** [comment]
Division last edited 11 дня тому by equivalentideas - Голосування востаннє оновлювалося 1 день /2-4 дні / 5-and more днів тому, [name]
View the edit history of this division - Дивитися історію оновлень цього голосування

We do not need "by" here

**Comment by equivalentideas** [comment]
I've made the changes above and extracted the issue about the pluralisations into #129 because it relates to other issues as well. I'm closing this with 3e08dbf
