### ISSUE TITLE
Translate friends page title

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#118]
Title is currently,

> Friends of #{member.full_name}

Where `member.full_name` is:

> "#{name} MP, #{electorate}"
- What should we change `full_name` to?
- What should the title translation be?

**Comment by orybiy** [comment]
Friends of #{member.full_name} - Друзі по голосуванню депутата/тки:  {member.full_name}

"What should we change full_name to?"
- please, give the link, I'm not sure that I understand this

**Comment by equivalentideas** [comment]
I've inserted the translation above for 'Friends of' in 8ef3ece.

This text is now “Друзі по голосуванню депутата/тки: Анатолій Євлахов MP, Виборчому округу №207” [for this page](https://tvfy-ukraine.oaf.org.au/people/rada/%D0%92%D0%B8%D0%B1%D0%BE%D1%80%D1%87%D0%BE%D0%BC%D1%83_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D1%83_%E2%84%96207/%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BB%D1%96%D0%B9_%D0%84%D0%B2%D0%BB%D0%B0%D1%85%D0%BE%D0%B2/friends).

> "What should we change full_name to?"
> please, give the link, I'm not sure that I understand this

@orybiy you won't be able to see the text on the page, it's for search engines and social media links. Here's an [example from They Vote For You in Google search](https://encrypted.google.com/search?hl=en&q=site%3Atheyvoteforyou.org.au%20friends%20of%20Malcomb%20turnbull#safe=off&hl=en&q=site:theyvoteforyou.org.au+friends+of+Malcolm+turnbull):

![screen shot 2015-11-30 at 4 45 56 pm](https://cloud.githubusercontent.com/assets/1239550/11464377/12e4c880-9782-11e5-8394-194cf9af210c.png)

In the example above, the 'full_name' text is "Анатолій Євлахов **MP**, Виборчому округу №207". What should this be in Ukrainian?

Thanks :)

**Comment by orybiy** [comment]
I've got it. thanks:)
Is it possible to do  in this way? 
Анатолій Євлахов MP, виборчий округ №207 - if elected in district
Анатолій Євлахов MP, [name of party] - if elected by party lists

**Comment by equivalentideas** [comment]
> Is it possible to do in this way? 

Yep, and I've made that change in 8430706

**Comment by equivalentideas** [comment]
@orybiy you can test this out by hovering your mouse over the tab in your browser on this page https://tvfy-ukraine.oaf.org.au/people/rada/Виборчому_округу_№37/Дмитро_Шпенов or this page https://tvfy-ukraine.oaf.org.au/people/rada/Виборчому_округу_№207/Анатолій_Євлахов , like this:

![img_4301](https://cloud.githubusercontent.com/assets/1239550/11494200/43995c34-9854-11e5-8796-ca32ba5ae22a.jpg)

Feel free to reopen this issue if there are problems :+1:
