### ISSUE TITLE
Translate "strong" policy vote option

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#121]
When you associate a vote with a policy you can say that supporters of the policy would have voted "yes" or "no". However for important votes (e.g. to pass a bill) you can also say "yes (strong)" or "no (strong)". There's an example here:

https://tvfy-ukraine.oaf.org.au/policies/1#divisions

We have the translation for "yes" (Так) and "no" (Ні) but we also need the translation for:

> Yes (strong)

and

> No (strong)

**Comment by orybiy** [comment]
I am not sure that we need this in Ukrainian TVFY. @lisoffsky ?

**Comment by lisoffsky** [comment]
@orybiy, it would be great to have it but I can't find a good translations. Can we say беззаперечно?
If no, than let's erase this

**Comment by orybiy** [comment]
Юра, я взагалі не розумію, про що йдеться і на основі яких даних виводиться
те 'беззаперечно'? Це треба пояснювати читачу, а в австр.варіанті це як
саме собою зрозуміле, видимо
29 нояб. 2015 г. 23:21 пользователь "lisoffsky" notifications@github.com
написал:

**Comment by lisoffsky** [comment]
okay, got you.
@henare can we have only have yes and no options, without (strong)? I think it can confuse people a lot.

**Comment by henare** [comment]
> can we have only have yes and no options, without (strong)? I think it can confuse people a lot.

It's currently an important part of how policy agreement is calculated - this is why you need to start creating policies on the site ASAP so you can see how they work and we can make any adjustments.

On the Australian and UK sites, "strong" votes are applied to most votes and "normal" votes are only used for procedural votes. Again, it's easiest to see once you start doing it. I'd suggest leaving the distinction and applying most votes as "strong" because of how this impacts the agreement calculation.

I think we could definitely change the language though. It could make sense to call "normal" votes "minor" votes - this applies to our sites too.

However I think this should be created as a separate issue once you've created some policies and see how they work. In the mean time we should still put in place a sensible translation for this as part of resolving this issue.

**Comment by orybiy** [comment]
Yes (strong) - Так (тверде)
No (strong) - Ні (тверде)

**Comment by henare** [comment]
:+1: thanks @orybiy!
