### ISSUE TITLE
Translate "totals"

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#123]
Shown on the [total row](https://github.com/OPORA/publicwhip/blob/develop/app/views/divisions/_summary.uk.html.haml#L80) of vote tables:

![selection_001](https://cloud.githubusercontent.com/assets/48945/11359327/3594ec00-92cf-11e5-91f4-c2a4fbca6d46.png)

**Comment by orybiy** [comment]
totals - Всього
