### ISSUE TITLE
Translate related divisions section

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#124]
At the bottom of vote pages we have a ["related divisions" section](https://tvfy-ukraine.oaf.org.au/divisions/rada/2015-11-13/4589#related-divisions) that displays other votes for the same bill as this division.

We need a translation for the title:

> Related divisions

And these sentences:

> Another division relating to the same bills as this one

The same with more than 1 related division:

> 7 divisions relating to the same bill as this one

Note that there are 2 sets of plurals that might be different in Ukrainian:

> 1 division, 3 divisions, 5 divisions

and

> "1 bill", more than "1 bills"

**Comment by orybiy** [comment]
Related divisions - Пов'язані голосування

Another division relating to the same bills as this one / to the same bills as this one  - Інше голосування, пов'язане з цими законопроектами / пов'язане з цим законопроектом

7 divisions relating to the same bill as this one - 1 голосування, пов'язане з цим законопроектом / 2-4 голосування, пов'язаних з цим законопроектом / [5 and more] голосувань, пов'язаних з цим законопроектом

1 division relating  to the same bill as this one /  to the same bills as this one - 1 голосування, пов'язане  з цим законопроектом / з цими законопроектами

relating to the same bill as this one - пов'язаних з цим законопроектом 
 relating to the same bills - пов'язаних з цими законопроектами
