### ISSUE TITLE
Layout of votes in table is inconsistent

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#126]
Sometimes the last type of vote 'Не голосували' wraps to a new line, and sometimes all the votes information is on a single line in the division votes table. These should be consistently all on one line if possible. It looks messy and confusing at the moment.

![screen shot 2015-11-30 at 3 43 21 pm](https://cloud.githubusercontent.com/assets/1239550/11463711/572877ba-977a-11e5-9f07-7f89e30a0fd5.png)

**Comment by equivalentideas** [comment]
Closed by 797bc14acdbf5fa7bf1e1b1d68a33ba4c7e9659b
![screen shot 2015-12-02 at 11 45 53 am](https://cloud.githubusercontent.com/assets/1239550/11519284/10843bf4-98ed-11e5-8a23-fedfe1ae64e2.png)

**Comment by henare** [comment]
Looks fancy :gem:
