### ISSUE TITLE
About page and navigation link text for the about page are different

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#127]
The link to the [About page](https://tvfy-ukraine.oaf.org.au/about) in the navigation is “Про нас” and on the page itself, the title is “Про проект”.

![screen shot 2015-11-30 at 4 17 19 pm](https://cloud.githubusercontent.com/assets/1239550/11464087/d0533676-977e-11e5-9eb5-86b4c16bbb92.png)

Unless this makes sense in Ukrainian, these should be the same for usability reasons. If the text is the same it's not ambiguous whether or not you are on the page for the navigation link you clicked.

If it makes sense for these to be the same, @orybiy @mmitre can you tell us which one it should be?

**Comment by orybiy** [comment]
Agree!
Let it be the same:

Про проект

It's more precise taking into account  the text below the page title
