### ISSUE TITLE
Devise notice messages need translation

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#130]
![screen shot 2015-12-01 at 11 01 29 am](https://cloud.githubusercontent.com/assets/1239550/11488513/2f2fb0a6-981b-11e5-9ac3-afb5c2a51110.png)

Looks like we can get all the devise message translations from the devise-i18n gem https://github.com/tigrish/devise-i18n/blob/master/rails/locales/uk.yml

**Comment by henare** [comment]
Great find & fix :postal_horn:
