### ISSUE TITLE
Translate licencing page 

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#131]
It's linked to in the footer so this should be translated: https://tvfy-ukraine.oaf.org.au/help/licencing

**Comment by orybiy** [comment]
Licencing - Авторські права
You are free to reuse/republish the parliamentary data in Вони голосують для тебе with a reference and link to this website. - Ти можеш повторно використовувати та публікувати розміщені на сайті _Вони голосують для тебе_ дані, за умови посилання та розміщення лінку на цей сайт.

Use the data - Використовуй дані

Access the data via our API. It is licensed under Open Data Commons Open Database License to the extent which we have rights to it. This is an attribution, share-alike licence, so the work you produce with this data must also share the result under a compatible open data licence.  -  Цей ресурс є безкоштовним, з відкритим вихідним кодом. Всі дані можуть бути використані повторно. Використовуй [наш API](інтерфейс програмування додатків). 

Always double check any data you use are correct. If you do find an error, please let us know and we'll do our best to correct it for everyone. - Завжди уважно перевіряй усі дані, які ти використовуєш. Якщо ти знайшов помилку, будь ласка, [напишипро це нам], і ми зробимо все можливе, щоб її виправити.

Use the software - Використовуй програмне забезпечення

Download the software on GitHub. You may use it and change it you as long as you release any changes you make under the terms of GNU Affero General Public License. - Завантаж програмне забезпечення на [GitHub]. Ти можеш використовувати його згідно з правилами [GNU Affero General Public License].
