### ISSUE TITLE
Person's full voting record page is slow

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#135]
It takes over a minute to show this page, for example: https://tvfy-ukraine.oaf.org.au/people/rada/Виборчому_округу_№207/Анатолій_Євлахов/divisions

It's because there are over 3,400 votes.

Paginating this will be a little harder as we currently go back [through all their membership history](https://github.com/OPORA/publicwhip/blob/develop/app/views/divisions/index_with_member.html.haml#L12-L13).

**Comment by equivalentideas** [comment]
> Paginating this will be a little harder as we currently go back through all their membership history.

Couldn't you extract that all into the controller to make an @divisions collection and then paginate that?

**Comment by henare** [comment]
I'm not sure, is that how it works?

**Comment by equivalentideas** [comment]
Yeah basically. I'll give it a go if you like.

**Comment by henare** [comment]
I'm surprised - assigning to you!

**Comment by equivalentideas** [comment]
> I'm surprised - assigning to you!

I may be completely wrong :) but we'll soon see.
