### ISSUE TITLE
Translate "attendance" on division items

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#138]
http://tvfy-ukraine.oaf.org.au/divisions/

![selection_001](https://cloud.githubusercontent.com/assets/48945/11523664/36069108-9918-11e5-9130-e36ef988051d.png)

Can we please get a translation for:

> 67% attendance

This means the percentage of people that attended a vote.

**Comment by orybiy** [comment]
Відвідуваність

**Comment by henare** [comment]
Perfect, thanks @orybiy :ok_hand:
