### ISSUE TITLE
Buy SSL certificate

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#14]
Once we've got a domain (#13) we need an SSL certificate.

**Comment by henare** [comment]
It's just a self signed one right now: https://github.com/OPORA/publicwhip/blob/ukraine/provisioning/roles/theyvoteforyou/tasks/main.yml#L63

**Comment by beastie87** [comment]
I added the new ssl certificate in /etc/nginx/conf/

**Comment by henare** [comment]
Looking good @beastie87. I've added it to the server repository: https://github.com/OPORA/publicwhip_server/commit/1ec70f39f83173b412121a192fbb49246f6b0008
