### ISSUE TITLE
Translate member page title

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#145]
The person page titles include "MP", I'm guessing this is wrong/hasn't been translated.

e.g. https://tvfy-ukraine.oaf.org.au/people/rada/Загальнодержавному_багатомандатному_округу/Сергій_Алєксєєв

![selection_001](https://cloud.githubusercontent.com/assets/48945/11582622/1d5a3f04-9aa5-11e5-99db-368bcb8d40a4.png)

So currently it's:

> # {person name}, MP #{electorate}

What should it be?

**Comment by lisoffsky** [comment]
Thank you for this, it would be great just to delete "MP"
We all know he is MP so no need in this. Everything else is consistent, in my opinion
