### ISSUE TITLE
Translate MP all votes meta title and description

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#151]
@orybiy @mmitre Could we please get Ukrainian translations for:
- All rebel votes — Віталій Чепинога MP, обраний в Раду за списком партії — Вони голосують для тебе
- A list of all votes in parliament where Віталій Чепинога MP voted against the majority of their party.
- Voting Record — Віталій Чепинога MP, обраний в Раду за списком партії — Вони голосують для тебе
- A list of all votes in parliament that Віталій Чепинога MP could have attended.

These are for:
- https://rada4you.org/people/rada/Загальнодержавному_багатомандатному_округу/Нестор_Шуфрич/divisions?filter=rebellions
- https://rada4you.org/people/rada/Загальнодержавному_багатомандатному_округу/Нестор_Шуфрич/divisions

**Comment by orybiy** [comment]
All rebel votes — Усі голосування проти фракції

A list of all votes in parliament where Віталій Чепинога MP voted against the majority of their party.- Список усіх голосувань у парламенті, під час яких [MP's name] голосував/ла проти більшості своєї фракції. 

Voting Record  -  Список голосувань

A list of all votes in parliament that Віталій Чепинога MP could have attended. - Список усіх голосувань у парламенті, під час яких [MP's name] мав/мала бути присутнім/ня.
