### ISSUE TITLE
Translate "Recent rebellions" and "View all rebellions"

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#152]
"Recent rebellions" is now the title of the rebellions section on the member page, which now only shows recent rebellions because the page was getting too big (#146). We also now link to a page with all the person's rebellions, "View all rebellions":

![screen shot 2015-12-07 at 6 03 34 pm](https://cloud.githubusercontent.com/assets/1239550/11621120/fdb70a96-9d0c-11e5-995d-e14ac102236e.png)

See https://rada4you.org/people/rada/Загальнодержавному_багатомандатному_округу/Нестор_Шуфрич/#rebellions

**Comment by equivalentideas** [comment]
Ping @orybiy @mmitre :)

**Comment by orybiy** [comment]
Recent rebellions - Останні голосування проти лінії фракції
View all rebellions - Дивитися усі голосування проти лінії фракції

**Comment by equivalentideas** [comment]
Closed by https://github.com/OPORA/publicwhip/compare/c494f3af5666...6ca023085959
