### ISSUE TITLE
API All divisions

### ISSUE THREAD

**Issue by beastie87** [OPORA/publicwhip#154]
very good it is request GET https://rada4you.org/api/v1/divisions.json?key=[api_key]  ->  return at most 100 results? but is the need to take more divisions and  and it would be convenient to use paging
Example  https://rada4you.org/api/v1/divisions.json?page=1&key=[api_key]
page = 1 return 1-100, page = 2 return 101-200...etc
if use start_date and end_date you need to know the specific date range, there is not good)

**Comment by henare** [comment]
Good call @beastie87 :+1: 

We should make this change when we do the Popolo compatible API, so I've added that as a comment on that issue https://github.com/openaustralia/publicwhip/issues/919#issuecomment-162707695 and I'll close this one.
