### ISSUE TITLE
"All divisions" API documentation should be clear about what you need to specify for the "house" parameter in Ukraine

### ISSUE THREAD

**Issue by beastie87** [OPORA/publicwhip#155]
Edit by @henare: You don't need to specify the "house" parameter in Ukraine so we should say that.

---

I am sorry
if GET https://rada4you.org/api/v1/divisions.json?end_date=2014-09-01&house=senate&start_date=2014-08-01&key=[api_key]                                        #house=senate
not works
elsif   GET https://rada4you.org/api/v1/divisions.json?end_date=2014-09-01&house=rada&start_date=2014-08-01&key=[api_key]                                           #house=rada
it is works
end

**Comment by henare** [comment]
This is working as it should - you need to specify the correct house name or none at all. In Ukraine the house is "rada" so this makes sense.

I'll change this issue to update the documentation.
