### ISSUE TITLE
Update is ukraine server

### ISSUE THREAD

**Issue by beastie87** [OPORA/publicwhip#156]
Sorry! I have a question.
Votes can be updated daily by running application:load:ukraine:vote_events without arguments. It will try to fetch all votes since the most recent one in the database until the present day.

application:load:ukraine:vote_events start is cron?  
Or use gem or aplications? 
Thank You!

**Comment by henare** [comment]
@beastie87 yes, the server automatically updates daily: https://github.com/OPORA/publicwhip_server/blob/master/roles/theyvoteforyou/tasks/main.yml#L96-L101

Does that answer your question?

**Comment by beastie87** [comment]
Thank you! Sorry @henare 
I did not seen  cron user root 
I now see that from the cron user deploy )

**Comment by henare** [comment]
No problem @beastie87 :+1: Keep the questions coming :smile:
