### ISSUE TITLE
Help — Frequently Asked Questions translation

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip#157]
Just in case it would be useful to have now.
I saved some English text to have connections.

**Допомога — Часті питання**

```
* Як працює проект Вони Голосують Для Тебе? (https://rada4you.org/help/faq#how)
* Який часовий період від покриває? (https://rada4you.org/help/faq#timeperiod)
* Що таке Голосування (https://rada4you.org/help/faq#division)
* Коли відбувається голосування? (https://rada4you.org/help/faq#division-occur) - this procedure doesn't exist in Ukraine. Let's delete this block
* Чому не всі рішення, прийняті у Раді, з'являються на Вони Голосують Для Тебе? (https://rada4you.org/help/faq#decisions) - Related to previous. Let's delete this block
* Чому не всі голосування мають описове узагальнення? (https://rada4you.org/help/faq#summaries)
* Що таке Політики та як це працює? (https://rada4you.org/help/faq#policies)
* Як визначити, підтримує депутат якусь із політик чи ні? (https://rada4you.org/help/faq#stance)
* Що таке "Проти фракції"? (https://rada4you.org/help/faq#rebel)
* What is a “Free Vote”? - Let's erase this. We don't have such practice
* Що таке відвідуваність? (https://rada4you.org/help/faq#attendance)
```

Let's erase a "rebellion figures" and tied divisions.

Вони Голосують Для Тебе збирає всі дані голосувань з порталу Верховної Ради (rada.gov.ua) та складає з них список голосувань, який ти можеш знайти в розділі Голосування (https://theyvoteforyou.org.au/divisions). Ти можеш шукати ці голосування (https://rada4you.org/search) або переглядати голосування, котрі пов'язані із якоюсь окремою політикою у розділі Політики (https://rada4you.org/policies) (щоб дізнатись більше про Політики див. Що таке Політики та як це працює? (https://rada4you.org/help/faq#policies)).

What time period does it cover?

На порталі Вони Голосують Для Тебе зібрані всі голосування VIII скликання Ради, тобто з листопада 2014 року. Нові голосування додаються одразу після їх публікації на офіційному порталі Верхової Ради. Ми не надаємо гарантії, що ці дані офіційні та фінальні, тому повідом нас (https://rada4you.org/about#contact), якщо знайдеш якісь фактологічні помилки.

Проект охоплює 422 народних депутати з 6 фракцій та 2 депутатських груп, які проголосували вже ХХХХ законопроектів. Загалом охоплено ХХХХХХХ поданих голосів депутатів, ХХХХХХ були проти більшості їхньої фракції/групи, що дає можливість порахувати рейтинг голосувань проти лінії фракцій/груп як ХХ%
Х авторів створили ХХ політик та підсумували Х голосувань.

What is a division?

Голосування - це офіційний розгляд законопроекту у Верховній Раді України. Законопроект - це офіційна пропозиція внести зміни до якогось закону або вчинити інші дії.
Під час голосування за окремий законопроект Рада умовно поділяється на 2 групи: ті, хто голосує За та ті, хто голосує Проти.

Why don’t all the divisions have edited summaries?

Коли ти натискаєш на посилання голосування (https://rada4you.org/divisions), тебе буде перенаправлено на результат, який буде містити опис цього голосування чи повідомлення про те, що нам потрібна чиясь допомога, щоб його зробити.
Зараз описи є лише у голосувань, котрі "прив'язані" до якоїсь із Політик (https://rada4you.org/policies). Дивися нашу сторінку Аналізу (https://rada4you.org/help/research), щоб дізнатись більше про те, як робляться описи голосувань.

What are Policies and how do they work?

Тут, на Вони Голосують Для Тебе, Політики (https://rada4you.org/policies) - це набори голосувань з якогось питання.

Ми обираємо та розробляємо окремі політики з різних причин. Наприклад, ми пріоритизуємо питання, на розгляді яких багато політиків голосували проти фракції/групи, або де були вільні голосування, тому що такі голосування стають гарними індикаторами індивідуальної поведінки політика (див. Що таке "Проти фракції"? (https://rada4you.org/help/faq#rebel)). Інші причини для вибору окремої політики включають питання, що важливі для виборців (e.g.) та високий рівень відвідуваності (див. Що таке відвідуваність (https://rada4you.org/help/faq#attendance) та Що таке "Проти фракції"? (https://rada4you.org/help/faq#rebel)).

How did you decide whether someone supports a policy or not?

Ми цього не вирішуємо. Позиція депутатів щодо Політики (https://rada4you.org/help/faq#policies) визначається тим, як вони голосують в Раді, під час розгляду (https://rada4you.org/help/faq#division) законопроектів, котрі стосуються Політики. Іншими словами — жодного значення не має те, що вони говорять, це лише підрахунок того, як вони голосують.

Однак, ми можемо не мати повної картини і ти можеш нам допомогти це виправити. Ось як це працює:

```
1. Після створення Політики (https://rada4you.org/users/sign_in) на Вони Голосують Для Тебе нам потрібно знайти Голосування (https://rada4you.org/divisions), що відносяться до цієї Політики (https://rada4you.org/policies) та пропрацювати те, якщо хтось, хто її підтримує, міг би проголосувати.
2. Як тільки Голосування прикріплено до Політики, Вони Голосують Для Тебе використовує голос кожної особи, щоб розрахувати де вони знаходяться відносно того, як голосували ті, хто підтримує цю політику — ти можеш легко знайти деталі та побачити технологічне пояснення натиснувши на окремого депутата на сторінці Політики.
```

На Вони Голосують Для Тебе є тисячі Голосувань. Там обов'язково будуть такі, що ще не прикріплені до Політик. Ти можеш допомогти нам поліпшити точність проекту Вони Голосують Для Тебе, знаходячи й класифікуючи такі Голосування до тих Політик, які тебе найбільше зачіпають.

What are “Rebel Voters”?

Коли депутат голосує не так, як більшість фракції/групи, до якої належить.

What do the "attendance" figures mean?

Відвідуваність - це відображення результатів обов'язкової письмової реєстрації депутата в день голосування.
Може бути багато різних причин з яких депутат має низький показних відвідуваності. У нас немає можливості показати тобі різницю між депутатами, які цього дня просто не прийшли в Раду, були зайняті іншими важливими справами чи просто не зареєструвались.

**Comment by equivalentideas** [comment]
> Let's erase a "rebellion figures"

This is what we link to from the 'explain rebellions' links around the site:

![screen shot 2015-12-08 at 11 46 05 am](https://cloud.githubusercontent.com/assets/1239550/11644588/613e4c70-9da1-11e5-9e62-79065c5f6805.png)

It does feel like a redundant section with your shorted version of the rebel voters section. I think people will get the correct meaning by just reading your "Rebel Voters" section:

> Коли депутат голосує не так, як більшість фракції/групи, до якої належить.

We will have to change these explanation links to go to the new section if we make this change.

Any thoughts on this @henare ?

**Comment by henare** [comment]
"rebellion figures" seems like a totally redundant section. I'm not sure why [we have it](https://theyvoteforyou.org.au/help/faq#rebellion).

> We will have to change these explanation links to go to the new section if we make this change.

Just use the `#rebellion` anchor on the section we are including and make sure there's no other links to `#rebel` instead.

**Comment by equivalentideas** [comment]
> Just use the #rebellion anchor on the section we are including and make sure there's no other links to #rebel instead.

Nice :+1:

**Comment by equivalentideas** [comment]
@henare do you know if it is possible and how to get the 'faction' and 'deputy group' figures for:

> Проект охоплює 422 народних депутати з 6 фракцій та 2 депутатських груп
> The project covers 422 deputies of the **6 factions** and **deputy groups 2**

The They Vote For You version of this is:

```
  The project contains
  %strong= number_with_delimiter(Member.select(:person_id).distinct.count)
  distinct Representatives and Senators from
  %strong= number_with_delimiter(Member.select(:party).distinct.count)
```

**Comment by equivalentideas** [comment]
So faction is just that party count, but I'm not sure what 'deputy groups' refers to in our data.

**Comment by equivalentideas** [comment]
Ok, I'm going to implement this as '2 депутатських груп' referring to the two types of deputies we have, list deputies and deputies elected by regions/electorates. So this wont be a dynamic number.

@lisoffsky please let me know if this is wrong ;-)

**Comment by equivalentideas** [comment]
Closed by:

92aa59b Translate title of help/faq page to Ukrainian
e2d1af4 Translate 'what is attendance' section of faq to Ukrainian
b9c09de Add template for Ukrainian translation of 'What is attendance' faq section
e73ae50 Translate 'What are rebel voters' section to Ukrainian
119db6b Add template for Ukrainian translation of 'what are Rebel Voters' section
6739162 Translate 'how did you decided–' section of FAQ to Ukrainian
e92ef0d Add template for Ukrainian translation of 'stance' section of faq
d007929 Translate help/faq 'What are Policies and how do they work?' section to Ukrainian
c8e8836 Add template for Ukrainian translation of help/faq 'Policies' section
63e3b2d Translate 'why don't all divisions have summaries' section to Ukrainian
2ac81bd Add template for Ukrainian translation of division summaries help section
b12ac83 Add Ukrainian translation of 'what is a division?' help section
e8ba61b Add template for Ukrainian translation of 'What is a division?' help section
91cb7ce Translate 'What time period does it cover?' section to Ukrainian
15f3766 Add template for Ukrainian translation of 'time_period' partial
3854a8d Remove redundant 'rebellions figures' section and move id to useful section
c4997b9 Translate 'how it works' FAQ section to Ukrainian
9dd115f Add template for Ukrainian translation of 'How does it work?' FAQ section
8a4d495 Remove 'tied division' section
0be3d0a Remove division procedure explanations that aren't relevant to Rada
8a80597 Add template for Ukrainian translation of help/faq page

If you could do a check over [the page](https://rada4you.org/help/faq) and raise any new issues @lisoffsky that would be great :smile: 

![screen shot 2015-12-08 at 4 24 54 pm](https://cloud.githubusercontent.com/assets/1239550/11648398/42fb0d08-9dc8-11e5-9180-fd7d3c78d1d2.png)
