### ISSUE TITLE
Translate "For #{some policy}"

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#158]
For each policy position we say if you support it then you would vote this way. So the policies are shown as, "For #{some policy}": https://rada4you.org/policies

We need a translation:

> "For #{some policy}"

**Comment by orybiy** [comment]
There is no need in this "For", let's remove it.
We have already considered this "for" in each policy title.

**Comment by henare** [comment]
@orybiy I'd suggest leaving it in the application and removing it from the manually entered title. The reason for this is that it makes it clear to the people creating policies that they should create one that is "for" or in support of something.

We decided to do this on They Vote For You because it makes the concept of policies clearer and easier to understand if they're all in support of something instead of having a mix of for and against.

**Comment by beastie87** [comment]
@henare sorry but, there is a tautology in for
it also desires @lisoffsky

**Comment by henare** [comment]
> sorry but, there is a tautology in for

Agreed :+1: I'd suggest removing the "for" part from the titles and hardcoding it back in the application, for the reasons I outlined above.

**Comment by beastie87** [comment]
I am commit and megre this fix
