### ISSUE TITLE
Translate 'How "never voted" is worked out' section

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#161]
We need the Ukrainian translation for:

> How "never voted" is worked out
> 
> Normally a person's votes count towards a score which is used to work out a simple phrase to summarise their position on a policy. However in this case Вячеслав Константіновський was absent during all divisions for this policy. So, it's impossible to say anything concrete other than that they have "never voted" on this policy.

See an example of this at the bottom of this page:
https://rada4you.org/people/rada/м_Київ/Вячеслав_Константіновський/policies/2

**Comment by orybiy** [comment]
never voted - ніколи не голосував

How "never voted" is worked out - Що означає "ніколи не голосував/ла"
Normally a person's votes count towards a score which is used to work out a simple phrase to summarise their position on a policy. However in this case Вячеслав Константіновський was absent during all divisions for this policy. So, it's impossible to say anything concrete other than that they have "never voted" on this policy.
Щоб визначити позицію депутата щодо тієї або іншої політики, ми враховуємо його/її голосування за/проти/утримався  під час проведення відповідних голосувань.  Однак у цьому випадку,  [MP's name] був/була відсутній/ня або не голосував/ла за  жодну зі складових відповідної політики. Таким чином, неможливо сказати що-небудь більш конкретне, окрім того, що депутат/ка ніколи "не голосував" за цю політику.

**Comment by beastie87** [comment]
Done
