### ISSUE TITLE
MPs info adjustements. for beastie87

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip#162]
@beastie87 please make small changes on this page https://rada4you.org/people

We see info duplication for each MP. 
Now it is 
{Олександр Абдуллін
Член фракції Фракція політичної партії "Всеукраїнське об'єднання "Батьківщина" у Верховній Раді України від партії Фракція політичної партії "Всеукраїнське об'єднання "Батьківщина" у Верховній Раді України}

So please make it like this
{Олександр Абдуллін
Член фракції Фракція політичної партії "Всеукраїнське об'єднання "Батьківщина" ~~у Верховній Раді України~~ від ~~партії Фракція~~ політичної партії "Всеукраїнське об'єднання "Батьківщина" у Верховній Раді України}

**Comment by beastie87** [comment]
I am waiting for confirmation of code revisions @henare or @equivalentideas
