### ISSUE TITLE
Translate title and introduction paragraph of *member all votes page*

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#163]
On [a members 'all votes' page](https://rada4you.org/people/rada/Загальнодержавному_багатомандатному_округу/Сергій_Алєксєєв/divisions), we need Ukrainian translations for the title:

> All Votes
> All votes Сергій Алєксєєв MP could have attended.

![screen shot 2015-12-09 at 10 37 49 am](https://cloud.githubusercontent.com/assets/1239550/11672040/0a51f81a-9e61-11e5-9dc5-9f66d582d69d.png)

ping @lisoffsky @orybiy

**Comment by lisoffsky** [comment]
All votes = Всі голосування
All votes Сергій Алєксєєв MP could have attended = Всі голосування на яких {Сергій Алєксєєв} міг віддати свій голос. 

@equivalentideas  do you mind if I assign this to @beastie87

**Comment by henare** [comment]
> @equivalentideas do you mind if I assign this to @beastie87 

Sounds good to me :+1:

**Comment by beastie87** [comment]
I am waiting for confirmation of code revisions @henare or @equivalentideas
