### ISSUE TITLE
Translate licencing page description 

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#166]
Shown to search engines, etc. for the page https://rada4you.org/help/licencing we need a translation for this please:

> The licences that make #{Settings.project_name}'s data and software free and open source.

Extracted from #131.

**Comment by orybiy** [comment]
The licences that make #{Settings.project_name}'s data and software free and open source. - Про умови використання даних і програмного забезпечення сайту {Settings.project_name}
