### ISSUE TITLE
Divisions appear too slowly

### ISSUE THREAD

**Issue by orybiy** [OPORA/publicwhip#173]
Please tell me how long does it usually take  for division to appear on the Division's page? More than 2  days pass and some important divisions on Budget ( http://w1.c1.rada.gov.ua/pls/zweb2/webproc4_1?pf3511=56449 )  still did not appear on the Division's page, is it ok? Thanks!

https://rada4you.org/divisions

**Comment by henare** [comment]
The scraper runs once a day to collect the votes and the application fetches them from the scraper once a day too. The rest is up to when the Rada puts the data on their website.

However this issue is actually because of a bug - we're missing votes on this date, see #174.
