### ISSUE TITLE
2015-12-24 votes missing

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#174]
The scraper errored https://github.com/openaustralia/ukraine_verkhovna_rada_votes/issues/13 so we're missing votes for this date.

**Comment by henare** [comment]
This sitting day also goes through to the next day so we should pay attention to how this will be handled by the scraper and the application.

**Comment by lisoffsky** [comment]
This kind of sittings are really extraordinary. So, could you please tell us how to resolve it. Unfortunately this day is very important, they voted for budget. 

Can this be related to another trouble, that new MPs are not appearing on website?
This one entered Parliament on December 24 http://itd.rada.gov.ua/mps/info/page/19623
because this one left http://itd.rada.gov.ua/mps/info/page/18040

**Comment by henare** [comment]
> Can this be related to another trouble, that new MPs are not appearing on website?

Yes, I'd say that's very likely.

To resolve this we need to:
- [ ] Check person scraper to ensure it's getting all the people correctly
- [ ] Get the votes scraper to reparse that day (it's likely we'll need to fix the timestamp on the votes that happened in the early hours of the next day)
- [ ] Run the import job on the server to import those votes

@lisoffsky if you'd like us to do this please let me know and I'll schedule it in.

**Comment by lisoffsky** [comment]
Thank you, @henare 
I'd like to ask @beastie87 to resolve this and it would be great if you can give him some advice when he needed.This way we can become more sustainable and bother you less in future:)

**Comment by henare** [comment]
@lisoffsky absolutely :+1:

**Comment by beastie87** [comment]
MPs Підберезняк Вадим Іванович  ID -> 19622 and
MPS Юзькова Тетяна Леонідівна ID  ->  19623 are https://morph.io/openaustralia/ukraine_verkhovna_rada_deputies
that is true but they are not in the data set  https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/data/Ukraine/Verkhovna_Rada/ep-popolo-v1.0.json 
Help me) 
Please tell us why track how information will be transmitted in this data set 
https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/data/Ukraine/Verkhovna_Rada/ep-popolo-v1.0.json 
Thank you!

**Comment by henare** [comment]
@beastie87 great job tracking down the problem! :sparkles: 

We need to trigger a rebuild of the data from the scraper into EveryPolitician, which is where _Вони голосують для тебе_ downloads its data from.

I've added instructions on how to do that: https://github.com/openaustralia/ukraine_verkhovna_rada_deputies#refreshing-data-in-everypolitician

And I've triggered a rebuild: https://github.com/everypolitician/everypolitician-data/pull/3289

Once that's been checked and merged by the maintaners the data will be up to date. To import it into _Вони голосують для тебе_ you can just wait for the daily cronjob to run or manually run the import from your machine:

```
bundle exec mina ukraine-production rake[application:load:ukraine:people]
```

**Comment by henare** [comment]
P.S. I think there are plans to make this automatic if this goes ahead: https://github.com/openaustralia/morph/issues/915

**Comment by beastie87** [comment]
MPs updates will be once a month or once in two months
I have questions:
When usually will https://github.com/everypolitician/viewer-sinatra/issues/2860 migration in master?
And also how  run the votes scraper https://github.com/openaustralia/ukraine_verkhovna_rada_votes to reparse of 2015-12-24 
Thank you!

**Comment by henare** [comment]
> When usually will everypolitician/viewer-sinatra#2860 migration in master?

It needs to be checked by the EveryPolitician maintainers first. They're usually pretty quick, I'd hope it's in the next day or two.

> And also how run the votes scraper https://github.com/openaustralia/ukraine_verkhovna_rada_votes to reparse of 2015-12-24 

Great question @beastie87 :four_leaf_clover: I've added [instructions on how to do this](https://github.com/openaustralia/ukraine_verkhovna_rada_votes#choosing-which-days-to-scrape) to the README.

**Comment by henare** [comment]
@beastie87 I just noticed a not authorised error on that scraper's settings page. I think you need to publicize your membership of @openaustralia to be able to access the settings of that scraper. I think you can do that here: https://github.com/orgs/openaustralia/people

**Comment by beastie87** [comment]
Thank you @henare 
I publicize my membership @beastie87 of @openaustralia, but is not to access  the settings of that scraper https://morph.io/openaustralia/ukraine_verkhovna_rada_votes/settings -> We're sorry, but something went wrong.

**Comment by henare** [comment]
Try logging out of morph.io and back in.

**Comment by beastie87** [comment]
Thank you @henare 
It is works)

**Comment by beastie87** [comment]
This issue is resolved) 
@lisoffsky and @orybiy  check this, If errors will open the issue
Thank you @henare

**Comment by henare** [comment]
That's amazing - great work @beastie87 :rocket:

**Comment by lisoffsky** [comment]
Oh, its magic for sure!
Thank you @beastie87 
many thanks to @henare for patience and advices!
