### ISSUE TITLE
Searching for MP who's changed faction shows two different entries

### ISSUE THREAD

**Issue by mmitre** [OPORA/publicwhip#20]
In the main page, search for гопко to find Hanna Hopko, who recently was removed from her faction.

The result page shows two different entries, one for her as a member of the Samopomich faction, one as her as a non-faction MP. 

Should only the active entry (e.g. non-faction) be shown here?

**Comment by henare** [comment]
That's a very good question!

I think only showing the latest entry makes more sense. @equivalentideas can you think of a reason now to do this on TVFY too?

**Comment by equivalentideas** [comment]
I've seen this happen on They Vote For You when MPs [change electorate](https://theyvoteforyou.org.au/search?utf8=%E2%9C%93&query=barnaby+joyce&button=Submit) or [become speaker](https://theyvoteforyou.org.au/search?utf8=%E2%9C%93&query=bronwin&button=Submit), but I haven't see it happen with someone changing party/faction. Is this the same issue?

Given that basically all the info on the different members pages is the same except for the title if they've changes electorate, I think it makes sense to have only one entry shown in the results and then show the the persons membership history on their personal page somehow.

Is that helpful?

**Comment by henare** [comment]
> I've seen this happen on They Vote For You when MPs change electorate or become speaker, but I haven't see it happen with someone changing party/faction. Is this the same issue?

Yes, becoming Speaker is (incorrectly) done by changing party in our current system.

> Given that basically all the info on the different members pages is the same except for the title if they've changes electorate, I think it makes sense to have only one entry shown in the results and then show the the persons membership history on their personal page somehow.
> 
> Is that helpful?

I think you're saying, "_only showing the latest entry makes more sense_".

**Comment by equivalentideas** [comment]
> I think you're saying, "only showing the latest entry makes more sense".

:+1: Yep.

And if that means the information that they were previously a member of a different party, or were speaker, I think we should make an issue about showing that stuff on the person page.

**Comment by henare** [comment]
Cool, thanks @equivalentideas.

> And if that means the information that they were previously a member of a different party, or were speaker, I think we should make an issue about showing that stuff on the person page.

We [already do](https://theyvoteforyou.org.au/people/representatives/mackellar/bronwyn_bishop), "_Before being Liberal Party Representative for Mackellar, Bronwyn Bishop was Speaker Representative for Mackellar and Liberal Party Representative for Mackellar._"

**Comment by equivalentideas** [comment]
> We already do, "Before being Liberal Party Representative for Mackellar, Bronwyn Bishop was Speaker Representative for Mackellar and Liberal Party Representative for Mackellar."

Amazing. It was actually me who created that lol
