### ISSUE TITLE
Server responds with 500 while searching

### ISSUE THREAD

**Issue by hmvs** [OPORA/publicwhip#231]
https://rada4you.org/search?utf8=%E2%9C%93&query=3251&button=Submit
Server responds with 500. Seems some server error there

**Comment by beastie87** [comment]
Thank you @hmvs.

**Comment by beastie87** [comment]
@hmvs what you would find associated with 3251?

**Comment by hmvs** [comment]
Tried to find all the laws with: №3251 
https://rada4you.org/divisions/rada/2016-06-16/7864

**Comment by hmvs** [comment]
@beastie87 seems search by pure numbers isn't working. will it be fixed?

**Comment by beastie87** [comment]
@hmvs I think that is already running 
if you believe that it does not work, please, open this issues 
Thank you!

**Comment by hmvs** [comment]
Yep, right now it's working. @beastie87  thanks
