### ISSUE TITLE
Encoding issues in API for vote result in division

### ISSUE THREAD

**Issue by hmvs** [OPORA/publicwhip#237]
Example: https://rada4you.org/api/v1/divisions/8261.json
`{"vote":"aye","member"`

**Comment by beastie87** [comment]
https://rada4you.org/help/data#division
votes   Сукупність голосів учасників голосування. Відображаються тільки ті депутати, які брали участь в цьому голосуванні
aye_votes   Кількість депутатів, які проголосували “ЗА”
number  Перше голосування в визначений день. Кожне наступне голосування пронумеровано відповідно.

**Comment by hmvs** [comment]
Ah. sorry. I thought "aye" it's something with encoding. My fault.
