### ISSUE TITLE
змінити контакти

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip#246]
Контакти   Twitter   facebook на стартовій (нижній лівий кут екрану) - зараз йдуть посилання не на "актуальні"
twitter - @rada4you
fb - fb.com/Dorogideputaty

**Comment by beastie87** [comment]
Змінено https://rada4you.org/ 
Я закриваю данне issues, якщо важаєте що це питання не вирішено відкрийти його знов)
