### ISSUE TITLE
додати у https://rada4you.org/help/faq

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip#247]
https://rada4you.org/help/faq додати блок

додати у 
Після створення Політики на Вони голосують для тебе потрібно знайти Голосування, які відповідають тематиці цієї Політики та «прикріпити» їх до неї, використовуючи опцію «Чи це голосування належить до однієї з політик?».
У відповідному полі дай відповідь, як би проголосував прихильник цієї Політики під час голосування, яке ти «прикріплюєш», - «так» або «ні»?

на наступне. див виділення
Після створення Політики на Вони голосують для тебе потрібно знайти Голосування, які відповідають тематиці цієї Політики та «прикріпити» їх до неї, використовуючи опцію «Чи це голосування належить до однієї з політик?».
У відповідному полі дай відповідь, як би проголосував прихильник цієї Політики під час голосування, яке ти «прикріплюєш», - «так» або «ні»?
**_див [відео про те як їх створювати](https://rada.oporaua.org/instrumenty/rada4you)_**

**Comment by beastie87** [comment]
додано https://rada4you.org/help/faq#policies
я закриваю данне issues так як питання вирішене, якщо важаєте що воно ще не вирішене, відкрийте будь ласка дане issues
