### ISSUE TITLE
знак % поблизу цифр на графіку

### ISSUE THREAD

**Issue by GS-0001** [OPORA/publicwhip#252]
від учасників тренінгу надійшла пропозиція
>**додати знак % поблизу цифр на графіку**

для новачків неочевидно, що то відсотки, а не кількість депутатів. також в у випадку, якщо графік звантажується у вигляді файлу та поширюється де-ін-де, то така ж ситуація

**Comment by beastie87** [comment]
This issue was moved to OPORA/visrada4you#5
