### ISSUE TITLE
Не підвантажується фото нардепа

### ISSUE THREAD

**Issue by zhemchuzhnykova** [OPORA/publicwhip#255]
Гайз, допоможіть, будь ласка.
На сайті R4U не підвантажується фото нардепа, який нещодавно зайшов до складу ВР https://rada4you.org/policies/42#maksymalno-holosuie

![default](https://user-images.githubusercontent.com/26894722/38604054-f4392806-3d77-11e8-911b-9cdf51848ab6.PNG)

Його фото можна витягти тут: http://itd.rada.gov.ua/mps/info/page/20626

**Comment by beastie87** [comment]
@zhemchuzhnykova дякую, я підтягнув нову фотку, щоб її побачити нажми Ctrl+F5 або дочикайся оновлення кешу чи очисти його
