### ISSUE TITLE
[Translation] Main Page Головна

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#29]
<table class="c23" cellpadding="0" cellspacing="0"><tbody><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c3">English Version</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c3">Ukrainian Version</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c3">Notes</span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">How does your MP vote on the issues that matter to you?</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span>Як депутати голосують за </span><span>питання</span><span class="c2">, які важливі для тебе?</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Find your representative by name</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Знайди свого депутата за ім’ям</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Not using postal code, correct? Don’t think we have the mapping, and it would be an issue for list MPs</span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Discover &amp; Share</span></p><p class="c0"><span class="c2">Discover how your representatives in parliament vote on issues you care about. You might be surprised by what you find. Share this with others and spread the word.</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Дізнатися і поділитися</span></p><p class="c0"><span class="c2">Дізнайся, як народні обранці голосували у парламенті за проекти рішень, які важливі для тебе. Це може тебе здивувати. Поділися з іншими, поширюй правду.</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c42">Make it better</span></p><p class="c0"><span class="c42">People like you are making votes in Parliament easier to use by summarising divisions and editing policies, just like Wikipedia. Fix-up mistakes or add something new—if you see something, do something.</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Not a priority feature, correct?</span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Use the data</span></p><p class="c0"><span class="c2">This is a free and open source public resource. Everything here can be reused in your own project. Use our API to remix, play and tell your stories about how they vote to change our laws.</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Використовуй дані</span></p><p class="c0"><span class="c2">Цей ресурс є &nbsp;безкоштовним, з відкритим вихідним кодом. Всі дані можуть бути використані повторно. Використовуй наш API (інтерфейс програмування додатків) та &nbsp;розкажи свою історію.</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Is the API something that OAF would expose for the site?</span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Supporting organisations of this OPORA project (NDI, USAID, Open North, Open Australia Foundation?)</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Партнери ОПОРИ у цьому проекті (NDI, USAID, Open North, Open Australia Foundation) </span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">An OPORA project</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Проект Громадської мережі &nbsp;ОПОРА </span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Links:</span></p><ul class="c28 lst-kix_2xfxwxozxrzu-0 start"><li class="c0 c26"><span class="c2">Contact &nbsp; </span></li><li class="c0 c26"><span class="c2">Twitter &nbsp;</span></li><li class="c0 c26"><span class="c2">Facebook</span></li><li class="c0 c26"><span class="c2">About</span></li><li class="c0 c26"><span class="c2">Help/FAQ</span></li><li class="c0 c26"><span class="c2">Recent changes</span></li><li class="c0 c26"><span class="c2">API</span></li></ul></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Посилання:</span></p><p class="c0 c38"><span>●</span><span class="c21">&nbsp; &nbsp; &nbsp;</span><span class="c2">Контакти</span></p><p class="c0 c38"><span>●</span><span class="c21">&nbsp; &nbsp; &nbsp;</span><span class="c2">Twitter </span></p><p class="c0 c38"><span>●</span><span class="c21">&nbsp; &nbsp; &nbsp;</span><span class="c2">Facebook</span></p><p class="c0 c38"><span>●</span><span class="c21">&nbsp; &nbsp; &nbsp;</span><span class="c2">Про нас</span></p><p class="c0 c38"><span>●</span><span class="c21">&nbsp; &nbsp; &nbsp;</span><span class="c2">Допомога/FAQ</span></p><p class="c0 c38"><span>●</span><span class="c21">&nbsp; &nbsp; &nbsp;</span><span class="c2">Останні зміни</span></p><ul class="c28 lst-kix_mc6k9kck5y40-0 start"><li class="c0 c26"><span class="c2">API (інтерфейс програмування додатків)</span></li></ul></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">This data and software are free and open source</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Усі дані та програмне забезпечення надаються з відкритим вихідним кодом та є вільними для поширення</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">report an issue</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Повідомити про проблему </span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td></tr></tbody></table>

**Comment by equivalentideas** [comment]
I've decided to leave the supporting orgs list for now, cause it's easiest to do that all at once a bit later. #44 relates to that too.

Aside from that and the TODOs above, which need translation help (ping @mmitre @lisoffsky ), this is done:
![screen shot 2015-11-12 at 2 32 50 pm](https://cloud.githubusercontent.com/assets/1239550/11109929/48120cca-894a-11e5-821e-68b3af01135a.png)

**Comment by mmitre** [comment]
Looks great to me....

**Comment by henare** [comment]
:point_up: extracted TODOs so we can close this.
