### ISSUE TITLE
Check vote page for errors and things that need doing

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#3]
Now that we're starting to see this first bit of voting data in the app we need someone to review it and log any bugs or changes that need doing.

The following vote is this one: http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=3106

![vote](https://cloud.githubusercontent.com/assets/48945/9983666/924137f6-6048-11e5-894f-5f165cc806f8.png)

**Comment by henare** [comment]
Are there any issues you can spot @mmitre @lisoffsky or can we close this?

**Comment by mmitre** [comment]
Ukraine has a fourth potential option for MP's when it comes to votes (as opposed to just 3 in Australia and other countries). MPs have the option of "Not Voting" but not being absent by being in the hall but not pressing the yes or no button. Should this additional state be reflected in this page?

**Comment by lisoffsky** [comment]
@mmitre,
I think you are right and it would be great to have such a state. The only correction, MP has three buttons: For, Against and Abstain (proof http://image.zn.ua/media/images/original/Nov2014/101659.jpg)
BUT. 
I'd love to call Mario's state "Refused to vote" - "Відмовився проголосувати" so this would give more explanation to public.
What do you think?

**Comment by lisoffsky** [comment]
Actually, an MP can have five different status options:
- For/Yes - Actively pushed the Yes button
- Against / No - Actively pushed the No button
- Abstain - Actively pushed the Abstain button
- Refused to Vote - The card is in, but did not press any button
- Absent - MP card is not in

**Comment by henare** [comment]
@mmitre @lisoffsky perfect, thanks :+1: I've added issue #71.

I guess another issue on this page is #65.

If there's nothing else, I'll close this.
