### ISSUE TITLE
[translation] individual division/vote page

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#37]
The individual vote page, e.g. https://tvfy-ukraine.oaf.org.au/divisions/rada/2015-10-08/4101 will need to be translated. Ping @mmitre @lisoffsky :smile:

**Comment by equivalentideas** [comment]
How does #27 'Downplay community editing features' impact the vote/division page?

Can people add summaries?

![screen shot 2015-11-11 at 11 55 32 am](https://cloud.githubusercontent.com/assets/1239550/11080808/b1f56b6c-886b-11e5-8fde-705b9688b670.png)

**Comment by mmitre** [comment]
Added a table to the translation doc for Olena to translate.

**Comment by orybiy** [comment]
please see the table in the translation doc

**Comment by equivalentideas** [comment]
Working through the table in the translation doc I got up to "There was 1 rebellion in this division". I've completed or raised issues for the earlier rows.

**Comment by henare** [comment]
All done or extracted into new issues.
