### ISSUE TITLE
Add more supporting orgs

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#44]
On the They Vote For You front page we have a long list of supporting orgs from all around. This demonstrates that this is a broad international movement for parliamentary openness and adds credibility to the project.

Currently, in the google doc, this project has:
- NDI
- USAID
- Open North
- OpenAustralia Foundation

I'm sure many of the groups that supported They Vote For You would want to support this project as well. If this is something OPORA would like to do, you can find links to all those groups with their logos in the list on https://theyvoteforyou.org.au @mmitre @lisoffsky @jnlandry

**Comment by lisoffsky** [comment]
Luke, thank you for this idea. 
We'd love to have all the orgs on our main page.
Should we email them asking about their permission or just post the logos and links?

**Comment by equivalentideas** [comment]
@lisoffsky I think you should email them to get their permission, as this is a separate project that wasn’t around when they signed up.

**Comment by henare** [comment]
@equivalentideas should we remove this section until we have supporting organisations to add?

**Comment by equivalentideas** [comment]
@henare:

> @equivalentideas should we remove this section until we have supporting organisations to add?

Either that or change the list to the 4 orgs above.

**Comment by orybiy** [comment]
Very important to add the RADA Program (funding organization):
![examp_urk](https://cloud.githubusercontent.com/assets/15835332/11165845/dc315e7a-8b24-11e5-921d-77a2af1dc04d.png)

**Comment by lisoffsky** [comment]
@orybiy,
I think this is for another website.
