### ISSUE TITLE
Translate '1000 shares' to Ukrainian

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#47]
![screen shot 2015-11-12 at 4 51 01 pm](https://cloud.githubusercontent.com/assets/1239550/11111529/0f42e9dc-895e-11e5-9586-8e280dbf326f.png)

When there are no shares, the text just reads 'Share'. This text is in the [social_share template](https://github.com/OPORA/publicwhip/blob/develop/app/views/application/_social_share.html.haml) and can be translated there. The text 'x shares' comes from a javascript file [shareCount.js](https://github.com/OPORA/publicwhip/blob/develop/app/assets/javascripts/shareCount.js).

Maybe we could specify the noun version 'shares' in a data attribute on the .social-share-heading element, and then do the translation there using our normal template system?

We need Ukrainian translations for:
- "Share" as a verb
- and "X shares" as a noun. This is "X поширень" , according to #33

**Comment by henare** [comment]
You can also make the translations available to [client side javascript](https://github.com/webhippie/gettext_i18n_rails_js). This is obviously overkill.

Unless it's pretty simple to do your solution @equivalentideas, I'd be inclined just to change the JS file for our MVP. What do you think?

**Comment by equivalentideas** [comment]
> Unless it's pretty simple to do your solution @equivalentideas, I'd be inclined just to change the JS file for our MVP. What do you think?

Yeah I think this is pretty simple, so I'll give it a ago for 10 min and if it's not straightforward I'll just change the js file to include the translation.

**Comment by henare** [comment]
Magic :tophat:

**Comment by equivalentideas** [comment]
I've done the translation for 'x shares' but **we still need the translation for the verb 'Share' as in 'share this with your friends'. If there is a more common word for this on Ukrainian websites, we should use that** @mmitre .
