### ISSUE TITLE
Add equivalent text for "Please note that our voting records start in 2006."

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#48]
On They Vote For You, at the bottom of an MPs voting record we say "Please note that our voting records start in 2006." This is because some MPs have been in Parliament longer than we have data for, so they might have voted differently before that and it wouldn't be reflected in the voting record we present.

![screen shot 2015-11-12 at 5 13 43 pm](https://cloud.githubusercontent.com/assets/1239550/11111806/d0b44cf8-8960-11e5-92ce-97b0d5fdb63d.png)

Do we need to say anything like this for the Ukrainian version of the site @mmitre @lisoffsky @jnlandry ? Something like 'Please note that our records only start in 2015'? What would be helpful to people reading this?

**Comment by lisoffsky** [comment]
Hi!
Can we just scrape all the information for this convocation so we really don't need this text? It is scrapable -  we fixed our parser two times in last month and every time we reparsed all the information again from the scratch.

**Comment by henare** [comment]
Hello @lisoffsky! Thank you for this helpful reply :smile: 

> Can we just scrape all the information for this convocation so we really don't need this text?

Yes, we've already scraped every vote for this convocation (as far as I know). It starts in [November 2014](https://tvfy-ukraine.oaf.org.au/divisions/all/2014-11).

So @lisoffsky, does this mean we should just remove this text?

**Comment by orybiy** [comment]
It worth noting that  'Please note that our records only start in Nov 2014'
Увага: наші дані щодо голосувань охоплюють період з листопада 2014 р.

**Comment by henare** [comment]
We can just use @orybiy's translation. I'll move this back to "ready".

**Comment by henare** [comment]
@orybiy there's also a link on that. Can you please show what text the link would be on too?

> Please note that [our voting records start in 2006](http://localhost:3000/help/faq#timeperiod).

**Comment by orybiy** [comment]
Увага: наші дані щодо голосувань охоплюють _період з листопада 2014 р._

**Comment by henare** [comment]
Thank you @orybiy!
