### ISSUE TITLE
translate division outcome summary .division_outcome_with_majority_strength

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#50]
Extracted from #33

Passed by a small/large majority: Прийнятий з малою/абсолютною підтримкою

Not passed by a small/large majority: Не прийнятий з малою/абсолютною підтримкою

**Comment by equivalentideas** [comment]
I've made that translations above in https://github.com/OPORA/publicwhip/compare/f190680211cf...3664c3122bb9 .

@orybiy @mmitre @lisoffsky could we please get the translations for the two missing variations bellow:
- Прийнятий/Не прийнятий з modest majority
- Прийнятий/Не прийнятий unanimously

![screen shot 2015-11-17 at 11 13 25 am](https://cloud.githubusercontent.com/assets/1239550/11198927/03be8e5a-8d1d-11e5-8d3a-3269e80389eb.png)

**Comment by orybiy** [comment]
Прийнятий/Не прийнятий з modest majority - Прийнятий/Не прийнятий з посередньою підтримкою
 Прийнятий/Не прийнятий unanimously - Прийнятий/Не прийнятий одноголосно

**Comment by henare** [comment]
:+1:
