### ISSUE TITLE
Translate .member_vote_with_type

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#51]
Extracted from #33

![screen shot 2015-11-13 at 11 14 15 am](https://cloud.githubusercontent.com/assets/1239550/11135315/f9c3b2d6-89f7-11e5-9d85-7329632e1559.png)

**Comment by equivalentideas** [comment]
I'll pull all the different versions of this text into a list for translation.

**Comment by equivalentideas** [comment]
Could we please have Ukrainian translations of these different voting options that could appear:
- {MP name} voted Yes
- {MP name} voted No
- {MP name} voted Abstention
- {MP name} voted Yes/No/Abstention, rebelling against {party/faction}
- {MP name} was absent

I think that's it, but @henare are there any types of votes missing?

See [example on They Vote For You](https://theyvoteforyou.org.au/people/representatives/wentworth/malcolm_turnbull#rebellions): "Malcolm Turnbull voted Yes, rebelling against the Liberal Party":
![screen shot 2015-11-14 at 12 52 16 pm](https://cloud.githubusercontent.com/assets/1239550/11161357/a0a6b20c-8ace-11e5-82dc-df86bbba72b5.png)

**Comment by henare** [comment]
> {MP name} voted Abstention

I think that should be `{MP name} abstained`.

> I think that's it, but @henare are there any types of votes missing?

Yes, there's also "did not vote": #71.

**Comment by orybiy** [comment]
- [x] {MP name} voted Yes  -  {MP name} проголосував/ла Так {i put "/" because the difference in endings of words depends on gender}  
- [x] {MP name} voted No - {MP name} проголосував/ла Ні 
- [x] {MP name} voted Abstention  - {MP name} проголосував/ла Утриматися
- [x] {MP name} voted Yes/No/Abstention, rebelling against {party/faction} проголосував/ла Так/Ні/Утриматися та виступив\ла цим проти лінії своєї фракції 
- [x] {MP name} did not vote, rebelling against {party/faction} - {MP name} не голосував/ла та виступив/ла цим проти лінії своєї фракції 
- [x] {MP name} was absent - {MP name} був/ла відусутній/ня
- [x] {MP name} did not vote - {MP name}  не голосував/ла

**Comment by henare** [comment]
Thanks @orybiy. Unfortunately we don't currently have the gender in the project. Is there a way to phrase this that isn't dependent on gender?

You can see how this phrase is used on people pages, e.g. https://tvfy-ukraine.oaf.org.au/people/rada/Виборчому_округу_№207/Анатолій_Євлахов

Ping @lisoffsky @mmitre

**Comment by orybiy** [comment]
You are right, it's very complicated. So we need to use both variants of verb's endings in the text like this : 
не голосував/ла
був/ла відусутній/ня

**Comment by lisoffsky** [comment]
@henare, the simple approach will be to use @orybiy advise and add wordings from previous comment.
Thanks, Olena

**Comment by equivalentideas** [comment]
@orybiy I've made those changes in [49245e59d8bf...cddb2e69d0b0](https://github.com/OPORA/publicwhip/compare/49245e59d8bf...cddb2e69d0b0). Could you please have a look at [this example page](https://tvfy-ukraine.oaf.org.au/people/rada/%D0%92%D0%B8%D0%B1%D0%BE%D1%80%D1%87%D0%BE%D0%BC%D1%83_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D1%83_%E2%84%9687/%D0%AE%D1%80%D1%96%D0%B9_%D0%94%D0%B5%D1%80%D0%B5%D0%B2'%D1%8F%D0%BD%D0%BA%D0%BE/divisions) to see if you can spot any problems? Thanks :)

![screen shot 2015-12-02 at 3 48 57 pm](https://cloud.githubusercontent.com/assets/1239550/11522568/528594ac-990c-11e5-8e03-9f44a8c4749e.png)

**Comment by henare** [comment]
I had to revert these commits because they broke the build.

**Comment by equivalentideas** [comment]
> I had to revert these commits because they broke the build.

Thanks for that @henare , my bad! I've fixed this with https://github.com/OPORA/publicwhip/commit/3e9cbb7566a82aee9f9995aa34331914fa03e134
