### ISSUE TITLE
Translate 'All possible friends'

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#54]
We got 'possible friends' in #33 but need the version for the 'all friends page', e.g. https://tvfy-ukraine.oaf.org.au/people/rada/%D0%92%D0%B8%D0%B1%D0%BE%D1%80%D1%87%D0%BE%D0%BC%D1%83_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D1%83_%E2%84%96207/%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BB%D1%96%D0%B9_%D0%84%D0%B2%D0%BB%D0%B0%D1%85%D0%BE%D0%B2/friends

**Comment by orybiy** [comment]
all possible friends - Усі друзі по голосуванню
