### ISSUE TITLE
Are translation of '4 times' and '1 time' the same?

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#56]
This is for the translation of the number of times an MP has rebelled, e.g:

> Malcolm Turnbull has voted against the majority of their party 1 time

Do both:

> Микола Мартиненко голосував проти лінії фракції **1 разів** часу набуття депутатських повноважень у Листопада 2014.

and

> Микола Мартиненко голосував проти лінії фракції **3 разів** часу набуття депутатських повноважень у Листопада 2014.

Make sense?

You can see an example of this here http://localhost:3000/people/rada/%D0%97%D0%B0%D0%B3%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%BD%D0%BE%D0%BC%D1%83_%D0%B1%D0%B0%D0%B3%D0%B0%D1%82%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D1%82%D0%BD%D0%BE%D0%BC%D1%83_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D1%83/%D0%9C%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0_%D0%9C%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%B5%D0%BD%D0%BA%D0%BE#rebellions

**Comment by orybiy** [comment]
1 раз
2-4 рази
5+ разів

Микола Мартиненко голосував проти лінії фракції 1 разів часу набуття депутатських повноважень у Листопада 2014 "  should be changed to
Микола Мартиненко голосував проти лінії фракції 1 раз **з** часу набуття депутатських повноважень у **листопаді** **2014 р.**

**Comment by henare** [comment]
OK the sentence now says:

> Микола Мартиненко голосував проти лінії фракції 1 раз з часу набуття депутатських повноважень у Листопада 2014 р.

or

> Микола Мартиненко голосував проти лінії фракції 3 рази з часу набуття депутатських повноважень у Листопада 2014 р.

or

> Микола Мартиненко голосував проти лінії фракції 740 разів з часу набуття депутатських повноважень у Листопада 2014 р.
