### ISSUE TITLE
Translations of MP page descriptions for social media and search

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#58]
Translations for text that will show up in Facebook, twitter, search etc:
- "Фракція Політичної партії "НАРОДНИЙ ФРОНТ" Representative for Загальнодержавному багатомандатному округу Володимир Шкварилюк’s votes in the Australian Parliament."
- "How does Володимир Шкварилюк vote on issues that matter to you?",
- "Discover how Фракція Політичної партії "НАРОДНИЙ ФРОНТ" Representative for Загальнодержавному багатомандатному округу Володимир Шкварилюк votes in the Australian Parliament.",

extracted from #33

**Comment by orybiy** [comment]
"Фракція Політичної партії "НАРОДНИЙ ФРОНТ" Representative for Загальнодержавному багатомандатному округу Володимир Шкварилюк’s votes in the Australian Parliament."
Як голосує у парламенті Володимир Шкварилюк, член фракції Політичної партії "НАРОДНИЙ ФРОНТ", обраний за партійними списками {"Party title"} - shoud be added here }

"How does Володимир Шкварилюк vote on issues that matter to you?"
Як Володимир Шкварилюк голосує за питання, які важливі для Тебе?

"Discover how Фракція Політичної партії "НАРОДНИЙ ФРОНТ" Representative for Загальнодержавному багатомандатному округу Володимир Шкварилюк votes in the Australian Parliament." 
Дізнайся, як голосує у парламенті Володимир Шкварилюк, член фракції Політичної партії "НАРОДНИЙ ФРОНТ", обраний за партійними списками {"Party title"}

**Comment by henare** [comment]
I've done the middle one but the others are a bit confusing with the substitutions. These are what we currently have:

> "#{member_party_type_place_name(member)}’s votes in the Australian Parliament."

and

> Discover how #{member_party_type_place_name(member)} votes in the Australian Parliament.

Where `member_party_type_place_name(member)` outputs this:

> #{member.party_name} Representative for #{member.electorate} #{member.name}

Maybe we should just replace that with the person's name?

@orybiy can you please answer the above question and then translate these?

**Comment by orybiy** [comment]
Probably you are right, let's replace that.

"#{member_party_type_place_name(member)}’s votes in the Australian Parliament." - Голосування {name(member)}’ у парламенті

Discover how #{name} votes in the Australian Parliament. -- Дізнайся, як {name(member)}  голосує у парламенті.

**Comment by henare** [comment]
Thanks @orybiy.

> "#{member_party_type_place_name(member)}’s votes in the Australian Parliament." - Голосування {name(member)}’ у парламенті

Here's an example of this now: "Голосування Антон Яценко’ у парламенті."

> Discover how #{name} votes in the Australian Parliament. -- Дізнайся, як {name(member)} голосує у парламенті. 

Example: "Дізнайся, як Антон Яценко голосує у парламенті."
