### ISSUE TITLE
Translate word "for" in "Позафракційні Верхо́вна Ра́да Украї́ни for Виборчому округу №215"

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#59]
Translate word "for" in "Позафракційні Верхо́вна Ра́да Украї́ни for Виборчому округу №215". I can't tell from the translation "представник фракції Х від області Y" which word is 'for' :)

See [Individual MP page](https://tvfy-ukraine.oaf.org.au/people/rada/%D0%97%D0%B0%D0%B3%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%BD%D0%BE%D0%BC%D1%83_%D0%B1%D0%B0%D0%B3%D0%B0%D1%82%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D1%82%D0%BD%D0%BE%D0%BC%D1%83_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D1%83/%D0%92%D0%BE%D0%BB%D0%BE%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%A8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%BB%D1%8E%D0%BA)

![screen shot 2015-11-13 at 11 49 32 am](https://cloud.githubusercontent.com/assets/1239550/11135777/af94d38e-89fc-11e5-9754-d8b0b67efa67.png)

This needs to be inserted here https://github.com/OPORA/publicwhip/blob/develop/app/helpers/members_helper.rb#L34

**Comment by orybiy** [comment]
"for" - ", обраний по"

But would be great if it is possible to make some changes:  
Фракція Політичної партії "НАРОДНИЙ ФРОНТ" Верхо́вна Ра́да Украї́ни for Загальнодержавному багатомандатному округу
"Верхо́вна Ра́да Украї́ни" there's no need in it.  can be deleted here and everywhere across MPs' pages.
" for Загальнодержавному багатомандатному округу" should be replaced with ", обраний за партійними списками {Party title}"   @lisoffsky, please advice!

**Comment by henare** [comment]
Waiting for a response from @lisoffsky.

**Comment by lisoffsky** [comment]
so, if we can erase "Верхо́вна Ра́да Украї́ни", that would be great.
for = обраний по

thank you

**Comment by henare** [comment]
Changing the sentence has made this a bit confusing so let's go back to what the sentences currently contain.

A current member:

> #{member.party_name} Верхо́вна Ра́да Украї́ни for #{member.electorate}

A former member:

> Former #{member.party_name} Верхо́вна Ра́да Украї́ни for #{member.electorate}

What should these now be?

**Comment by lisoffsky** [comment]
so is it possible to make the change?
To change on MP page text “for Загальнодержавному багатомандатному округу” on “обраний в Раду за списком партії” (means: was elected by party list)

**Comment by henare** [comment]
@lisoffsky I've made that change on #141.

So back to the original question:

> A current member:
> 
> > #{member.party_name} Верхо́вна Ра́да Украї́ни for #{member.electorate}
> 
> A former member:
> 
> > Former #{member.party_name} Верхо́вна Ра́да Украї́ни for #{member.electorate}
> 
> What should these now be?

I'm now wondering if you'd like to display something quite different here, which is also possible. What do you think?

**Comment by lisoffsky** [comment]
#{member.party_name} Верхо́вна Ра́да Украї́ни=у Верховній Раді України
for= обраний по #{member.electorate}

Former=Вибув

I was looking for issue I submitted two days ago but couldn't find so I'm writing here.
I MP was elected in single mandate district can add his oblast after district number?
e.g. this guy elected by {Виборчому округу №45} and change to {Виборчому округу №45 (Донецька область)}

https://tvfy-ukraine.oaf.org.au/people/rada/%D0%92%D0%B8%D0%B1%D0%BE%D1%80%D1%87%D0%BE%D0%BC%D1%83_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D1%83_%E2%84%9645/%D0%AE%D1%85%D0%B8%D0%BC_%D0%97%D0%B2%D1%8F%D0%B3%D1%96%D0%BB%D1%8C%D1%81%D1%8C%D0%BA%D0%B8%D0%B9

**Comment by henare** [comment]
> #{member.party_name} Верхо́вна Ра́да Украї́ни=у Верховній Раді України
> for= обраний по #{member.electorate}
> 
> Former=Вибув

I've made this change in 34ddab08b399ae3f5020c48457ab44d60c6a8e83 but I think it's still not right. If it's not please open a new issue with the changes you want. This one has become a bit confusing.

> I was looking for issue I submitted two days ago but couldn't find so I'm writing here.
> I MP was elected in single mandate district can add his oblast after district number?
> e.g. this guy elected by {Виборчому округу №45} and change to {Виборчому округу №45 (Донецька область)}

In https://github.com/openaustralia/ukraine_verkhovna_rada_deputies/issues/6 we changed the constituency for these MPs to be the region only so I think that's fixed. Please open another issue if it's not.
