### ISSUE TITLE
Translate "explain attendance"

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#62]
![screen shot 2015-11-13 at 11 54 20 am](https://cloud.githubusercontent.com/assets/1239550/11135863/590c0a86-89fd-11e5-9148-a0b2f68aaafe.png)

see:
https://tvfy-ukraine.oaf.org.au/people/rada/%D0%97%D0%B0%D0%B3%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%BD%D0%BE%D0%BC%D1%83_%D0%B1%D0%B0%D0%B3%D0%B0%D1%82%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D1%82%D0%BD%D0%BE%D0%BC%D1%83_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D1%83/%D0%92%D0%BE%D0%BB%D0%BE%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%A8%D0%BA%D0%B2%D0%B0%D1%80%D0%B8%D0%BB%D1%8E%D0%BA

**Comment by orybiy** [comment]
Пояснити відвідуваність
