### ISSUE TITLE
Translate, with link " Translate "No policies match this person's votes. You can edit or make a policy that will appear here.""

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#63]
Translate "No policies match this person's votes. You can [edit or make a policy](#) that will appear here."

With the translation, please include which words should have the link on them :)

**Comment by orybiy** [comment]
Політик, які відповідають цьому голосуванню депутата, немає. Ви можете **запропонувати власну політику**, яка з'явиться тут.
