### ISSUE TITLE
Translation for "Policy last edited {time} ago by luke"

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#66]
![screen shot 2015-11-13 at 12 23 13 pm](https://cloud.githubusercontent.com/assets/1239550/11136303/5928886a-8a01-11e5-8722-0618693273b0.png)

**Comment by orybiy** [comment]
Політика востаннє оновлювалася {time} тому [by Name]

**Comment by henare** [comment]
OK it now says,

> Політика востаннє оновлювалася близько 4 години тому **by** henaredegan

There's still "by" not translated (highlighted above).

There's also the tooltip:

> View the edit history of this policy.

**Comment by orybiy** [comment]
We don't need translation of "by" here and everywhere, so : 

Політика востаннє оновлювалася близько 4 години тому by henaredegan - Політика востаннє оновлювалася близько 4 години тому, [name]

View the edit history of this policy - Дивитися історію оновлень цієї політики

**Comment by equivalentideas** [comment]
> We don't need translation of "by" here and everywhere, so :

I've removed 'by' with 3e08dbf.

> View the edit history of this policy - Дивитися історію оновлень цієї політики

I've made that change in 7e78a9670d6623914d6d5ae2f6e23bdab39a5470.

The pluralisation issue has been extracted to #129 so I'll close this issue :hammer:
