### ISSUE TITLE
Translate "Change title and definition of policy"

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#69]
This is the title text on edit policy links:

![screen shot 2015-11-13 at 12 44 09 pm](https://cloud.githubusercontent.com/assets/1239550/11136618/424a8442-8a04-11e5-84d2-73a192362b57.png)

Find code at https://github.com/OPORA/publicwhip/blob/develop/app/views/policies/_page_header.uk.html.haml#L7

**Comment by orybiy** [comment]
Зміни назву та опис політики
