### ISSUE TITLE
Translate "Skip to Relevant Divisions for this policy."

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#70]
This is the title/helper text on the link to a policy’s divisions:
![screen shot 2015-11-13 at 12 56 14 pm](https://cloud.githubusercontent.com/assets/1239550/11136780/f6466f64-8a05-11e5-9eed-ac18ea23ae3b.png)

Find code here https://github.com/OPORA/publicwhip/blob/develop/app/views/policies/show.uk.html.haml#L10

**Comment by orybiy** [comment]
Перейти до відповідних голосувань за цю політику
