### ISSUE TITLE
Translate 'Subscribed' as in 'you are subscribed to this policy

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#72]
When you are subscribed, the subscribe button says 'Subscribed':

![screen shot 2015-11-13 at 2 25 27 pm](https://cloud.githubusercontent.com/assets/1239550/11138120/76ecd2dc-8a12-11e5-8725-3b39c3146865.png)

This is low priority because only people who are signed up as site editors will see this.

**Comment by orybiy** [comment]
Відстежується

Right, @lisoffsky ?
як в укр.мовному фейсбуці). а то "Ти вже підписаний" - задовга назва

**Comment by lisoffsky** [comment]
Yes! thanks @orybiy
