### ISSUE TITLE
Translate "These divisions relate to the policy “<policy name>”. Compare how a supporter of the policy would have voted to the division outcome."

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#73]
This is for the list of votes on an individual policy page:

![screen shot 2015-11-13 at 2 39 34 pm](https://cloud.githubusercontent.com/assets/1239550/11138288/792645c2-8a14-11e5-8683-e094855bcff3.png)

**Comment by orybiy** [comment]
Це голосування стосується політики [policy name]. Аналізуй, хто і як вплинув на результат голосування.
