### ISSUE TITLE
Text for 'help us add more divisions to policy'

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#74]
From the translation table on #26 it sounds like the text for this section should change to something more like “If you know of other votes that relate to this policy let us [know via email](#)” ?

<table>
  <thead>
    <tr>
      <th>English Version</th>
      <th>Ukrainian Version</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>If you know of other divisions that relate to this policy, you can add them in the Votes section of that division‘s page.</td>
      <td>Якщо ви знаєте інші голосування, що відносяться до цієї політики, ви можете додати їх у розділ Голосування.</td>
      <td>Link to a mailto to send opora the information? (see #27 )

Yes</td>
    </tr>
  </tbody>
</table>

![screen shot 2015-11-13 at 2 47 54 pm](https://cloud.githubusercontent.com/assets/1239550/11138394/bb139e8e-8a15-11e5-9726-256d2a79a19c.png)

**Comment by mmitre** [comment]
Will this be exposed if we won't expose the community editing bits per #27?

**Comment by henare** [comment]
@mmitre good question. Assigning back to @equivalentideas.

**Comment by orybiy** [comment]
"If you know of other votes that relate to this policy let us know via email”
Translation:
Якщо Ти знаєш про інші **голосування**, що стосуються цієї політики, **напиши нам**.
