### ISSUE TITLE
Translate title/helper text of share buttons

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#75]
This is the text that you see when you hover over the share links with your mouse, or are using a screen reader:
- Share on Twitter
- Share on Facebook

![screen shot 2015-11-13 at 2 56 14 pm](https://cloud.githubusercontent.com/assets/1239550/11138478/d27e2b6a-8a16-11e5-8559-f2b0aaaed01c.png)
![screen shot 2015-11-13 at 2 56 08 pm](https://cloud.githubusercontent.com/assets/1239550/11138479/d2801cb8-8a16-11e5-9a18-58a7f1afbdd8.png)

**Comment by lisoffsky** [comment]
Let's use

```
Share on Twitter - Поширити у Facebook
Share on Facebook -  Поширити у Twitter
```
