### ISSUE TITLE
Translate main page links

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#76]
From #29:

Which words should the links go on in text here "Дізнайся, як народні обранці голосували у парламенті за проекти рішень, які важливі для тебе. Це може тебе здивувати. Поділися з іншими, поширюй правду." and here "Цей ресурс є  безкоштовним, з відкритим вихідним кодом. Всі дані можуть бути використані повторно. Використовуй наш API (інтерфейс програмування додатків) та  розкажи свою історію."? see:
![screen shot 2015-11-11 at 5 27 00 pm](https://cloud.githubusercontent.com/assets/1239550/11085381/a764e5c8-8899-11e5-9c64-e28126876035.png)

**Comment by mmitre** [comment]
народні обранці 
проекти рішень, які важливі для тебе

відкритим вихідним кодом
наш API

**Comment by orybiy** [comment]
Mario, you are right!
народні обранці 
 проекти рішень, які важливі для тебе
 з відкритим вихідним кодом
наш API

**Comment by henare** [comment]
Great stuff, thank you @mmitre and @orybiy :tulip:
