### ISSUE TITLE
Translate home page meta description

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#77]
From #29:

Translation for the home page <meta> description: "Forget what politicians say. What truly matters is what they do. And what they do is vote, to write our laws which affect us all."

**Comment by orybiy** [comment]
Забудь, що говорять політики. По-справжньому важать лише їхні дії. Слідкуй за тим, як депутати голосують і дізнавайся про їхню справжню позицію щодо питань, які впливають на нас усіх.
