### ISSUE TITLE
Translate "former"

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#78]
From #31:

The word "[Former](https://github.com/OPORA/publicwhip/blob/develop/app/views/members/_members.html.haml#L15)" to mean someone no longer in parliament, e.g. https://tvfy-ukraine.oaf.org.au/people/rada/Виборчому_округу_№121/Богдан_Матківський

**Comment by orybiy** [comment]
Колишній депутат

**Comment by henare** [comment]
We'll do this as part of #59 now.
