### ISSUE TITLE
Translate explanation of how policy positions are calculated to Ukrainian

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#79]
Here's the english version of the explanation of how votes are calculated:

> The MP's votes count towards a weighted average where the most important votes get 50 points, less important votes get 10 points, and less important votes for which the MP was absent get 2 points. In important votes the MP gets awarded the full 50 points for voting the same as the policy, 0 points for voting against the policy, and 25 points for not voting. In less important votes, the MP gets 10 points for voting with the policy, 0 points for voting against, and 1 (out of 2) if absent.
> 
> Then, the number gets converted to a simple english language phrase based on the range of values it's within.

Here’s where this appears: https://tvfy-ukraine.oaf.org.au/people/rada/Загальнодержавному_багатомандатному_округу/Сергій_Власенко/policies/1

We also need translations of the table headers and the other text underneath the table.

![screen shot 2015-11-13 at 3 30 28 pm](https://cloud.githubusercontent.com/assets/1239550/11138840/af618690-8a1b-11e5-8938-342d98f3b430.png)

**Comment by henare** [comment]
Ping @lisoffsky @orybiy @mmitre

**Comment by lisoffsky** [comment]
Well, I think this is it

The MP's votes count towards a weighted average where the most important votes get 50 points, less important votes get 10 points, and less important votes for which the MP was absent get 2 points. In important votes the MP gets awarded the full 50 points for voting the same as the policy, 0 points for voting against the policy, and 25 points for not voting. In less important votes, the MP gets 10 points for voting with the policy, 0 points for voting against, and 1 (out of 2) if absent.
Then, the number gets converted to a simple english language phrase based on the range of values it's within.

Голосування депутата рахуються як зважене середнє, де найважливіші голосування отримують 50 балів, менш важливі 10 балів, а ще менш важливі голосування на яких депутат був відсутній отримують 2 бали. Під час важливих голосувань депутат отримую повні 50 балів за голосування відповідно до політики, 0 балів за голосування проти і 25 за неголосування. В менш важливих голосуваннях депутат отримує 10 балів за голосування відповідно до політики, 0 за голосування проти і 1 (з двох), якщо відсутній.
Після цього, цифри конвертуються в прості фрази на основі діапазону значень в який потрапляє депутат.

 No of votes = Кількість голосувань
Points = Балів
Out of = З можливих
 Most important votes (50 points) = Найважливіші голосування (50 балів) 
 MP voted with policy = Голосувань відповідно політики
MP voted against policy = Голосувань проти політики
MP absent = Відсутній
Less important votes (10 points) = Менш важливі голосування (10 балів) 
 MP voted with policy = Голосувань відповідно політики
MP voted against policy = Голосувань проти політики
MP absent = Відсутній
 Less important absentees (2 points) = Відсутній на менш важливих (2 бали) 
MP absent = Відсутній*
Total = Всього

{ *Pressure of other work means MPs or Senators are not always available to vote – it does not always indicate they have abstained. Therefore, being absent on a less important vote makes a disproportionatly small difference. }
*Виконуючи інші обов'язки депутат не завжди має можливість голосувати - це не завжди відображає те, що він утримується. Внаслідок цього відсутність  на менш важливих голосуваннях робить різницю диспропорційно малою.

{ Agreement score = MP's points / total points = 50 / 50 = 100%. }
Узгоджений розрахунок = Бали депутата / Балів всього = 50 / 50 = 100%
And then = І потім
 between 95% and 100% becomes "very strongly for" = між 95% та 100% означатиме "Максимально голосує за" 
 between 85% and 95% becomes "strongly for" = між 85% та 95% означатиме "Послідовно голосує за"
between 60% and 85% becomes "moderately for"  = між 60% та 85% означатиме  "Переважно голосує за"
between 40% and 60% becomes "a mixture of for and against" = між 40% та 60% означатиме "Суміш за та проти"
 between 15% and 40% becomes "moderately against" = між 40% та 60% означатиме "Переважно голосує проти"
between 5,0% and 15% becomes "strongly against" між 5,0% та 15% означатиме "Послідовно голосує проти"
between 0,0% and 5,0% becomes "very strongly against"  = між 0,0% та 5,0% означатиме "Максимально голосує проти"

**Comment by equivalentideas** [comment]
Closed by https://github.com/OPORA/publicwhip/compare/34ddab0...c494f3af5666

![screen shot 2015-12-08 at 6 02 31 pm](https://cloud.githubusercontent.com/assets/1239550/11649696/e39a9b04-9dd5-11e5-84f3-3791d29ec030.png)

@lisoffsky Could you have a look over a page like this https://rada4you.org/people/rada/Сумська_область/Олег_Медуниця/policies/8#ratioexpl and reopen this issue if you find any errors? Thanks!
