### ISSUE TITLE
Check translation for “How <Name> voted compared to someone who believes that <description>”

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#82]
English:

> How `<Name>` voted compared to someone who believes that `<description>`

Ukrainian provided in #32 is:

> Як `<Name>` голосував у порівнянні з `<Name>`, який вважає, що `<description>`

This seems to me like “someone” has been substituted for <Name>?

[View this on the test site here](https://tvfy-ukraine.oaf.org.au/people/rada/%D0%97%D0%B0%D0%B3%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%BD%D0%BE%D0%BC%D1%83_%D0%B1%D0%B0%D0%B3%D0%B0%D1%82%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D1%82%D0%BD%D0%BE%D0%BC%D1%83_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D1%83/%D0%A1%D0%B5%D1%80%D0%B3%D1%96%D0%B9_%D0%92%D0%BB%D0%B0%D1%81%D0%B5%D0%BD%D0%BA%D0%BE/policies/1) using the test policy with description “policies should be tested (but this can be changed to a real one later)”:

![screen shot 2015-11-13 at 3 56 56 pm](https://cloud.githubusercontent.com/assets/1239550/11139116/75f26a6a-8a1f-11e5-96f2-77e0f880ed54.png)

**Comment by orybiy** [comment]
You're right, it should be that way:

Як [Name] голосував у порівнянні з прихильниками [ only first sentence of the description, please! Otherwise, we'll have great  problems with endings in words]

@lisoffsky ?

**Comment by henare** [comment]
I'm still not clear on what we need to do here so I'll await clarification from @lisoffsky and @orybiy.

**Comment by lisoffsky** [comment]
@henare, let's make it this way
Як [Name] голосував у порівнянні з тими, хто вважає, що [description]

@orybiy, fyi:)

**Comment by henare** [comment]
Perfect, thanks @lisoffsky :smile:
