### ISSUE TITLE
Translate "Votes held in Australian in parliament. These votes, called divisions, help shape legislation that affects us all."

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#83]
The page description for the divisions page, which will appear in search engines and social media is:

> Votes held in Australian in parliament. These votes, called divisions, help shape legislation that affects us all.

We need Ukrainian translation of this please. I image the text would change too as you probably don't have to explain the term 'divisions' like we do.

**Comment by orybiy** [comment]
Votes held in Australian in parliament. These votes, called divisions, help shape legislation that affects us all - 
Перелік голосувань у парламенті, результати яких впливають на всіх нас.
