### ISSUE TITLE
Is the “learn more” about divisions/votes link and text needed for the Ukrainian version?

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#84]
On the Australia They Vote For You we have a link for people to learn more about divisions:

![screen shot 2015-11-13 at 4 34 03 pm](https://cloud.githubusercontent.com/assets/1239550/11139507/7461bb7e-8a24-11e5-81c3-4b2bb62b1c1d.png)

A big reason for this is that the term “division” is not widely understood in Australia. [The explanation text on the help page](https://theyvoteforyou.org.au/help/faq#division) explains how votes work in the different houses of Australia's parliament.

Is this necessary in the Ukrainian version?

![screen shot 2015-11-13 at 4 37 08 pm](https://cloud.githubusercontent.com/assets/1239550/11139529/d418eb64-8a24-11e5-96f5-060e8c4e7af4.png)

**Comment by orybiy** [comment]
Yes, we need such a link. 
 In the explanation text on the help page we''ll explain the difference between voting yes/no/refrain/not vote/ etc.

**Comment by henare** [comment]
Thanks @orybiy - we'll keep it in :+1:
