### ISSUE TITLE
Translation for edited vote notice

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#85]
On the [votes page](https://tvfy-ukraine.oaf.org.au/divisions/all/2014), votes that have had summaries added get a notice like 'edited 20 days ago'.

We'll need the full Ukrainian for 'edited менше 1 хвилини ago'.

![screen shot 2015-11-13 at 5 23 38 pm](https://cloud.githubusercontent.com/assets/1239550/11140146/50f500a4-8a2b-11e5-9519-0b9de559da30.png)

**Comment by lisoffsky** [comment]
Let's try this way
edited менше 1 хвилини ago - оновлено менше 1 хвилини тому
but when it is 2 and more minutes the word "хвилини" in Ukrainian changes to "хвилин"
