### ISSUE TITLE
Show additional vote options in party summary

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#89]
We currently display the number of "yes" and "no" votes. If no one voted yes or no we just say "absent".

In Ukraine you can also abstain or not vote. We need to display these numbers in the summary too.

For example, see this vote where the party line was to abstain:

![selection_001](https://cloud.githubusercontent.com/assets/48945/11172595/0bb78c16-8c5e-11e5-84e3-f5ec5efdaea5.png)

And in the totals at the bottom of the table.

**Comment by henare** [comment]
Assigning @equivalentideas to look at the front-end design changes.

**Comment by equivalentideas** [comment]
I've added the abstentions: ![screen shot 2015-11-16 at 3 40 15 pm](https://cloud.githubusercontent.com/assets/1239550/11174485/61671a90-8c78-11e5-81d1-cf3c3268bbdf.png)

**Comment by equivalentideas** [comment]
I'll add not_voting votes now

**Comment by equivalentideas** [comment]
I've done this and also replaced the dash separators with whitespace. With 4 vote types the table was looking really messy with the dashes. I think this is clearer:

![screen shot 2015-11-16 at 4 42 03 pm](https://cloud.githubusercontent.com/assets/1239550/11175007/0601342a-8c81-11e5-8315-7bd4caae4a9f.png)
