### ISSUE TITLE
Translate short division summary that gets shown in social media

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#94]
Could we please get the Ukrainian for:

> Ukrainian Rada vote Прийнятий, 14.07.2015, 17:54

**Comment by lisoffsky** [comment]
Could you please give us a link?

**Comment by henare** [comment]
@lisoffsky I'm pretty sure it's [this](https://github.com/OPORA/publicwhip/blob/develop/app/helpers/divisions_helper.rb#L246-L249), which is displayed when a vote is shared on Facebook/Twitter (used, for example, [here](https://github.com/OPORA/publicwhip/blob/develop/app/views/divisions/show.uk.html.haml#L4)).

The phrases is:

> "Australian #{house_name} vote #{outcome}, #{division_date_and_time}"

We already have [the translations for `outcome`](https://github.com/OPORA/publicwhip/blob/develop/locale/uk/app.po#L24-L28).

Does that help?

**Comment by lisoffsky** [comment]
It is a bit complicated because of endings in Ukrainian:)
Can we shift the words order? It would be easier to put the status (Passed, Rejected) and then words.

"Ukrainian Rada vote" Прийнятий, 14.07.2015, 17:54 = Прийнятий "у Верховній Раді", 14.07.2015. 17:54

**Comment by henare** [comment]
An example after the change in 307053c:

> Не прийнятий у Верховній Раді, 17.06.2015, 14:11

**Comment by lisoffsky** [comment]
looks great! Thanks!

On Thu, Nov 19, 2015 at 8:07 AM, Henare Degan notifications@github.com
wrote:

> An example after the change in 307053c
> https://github.com/OPORA/publicwhip/commit/307053c7afff6869662db2b33a3f32b44096e7cc
> :
> 
> Не прийнятий у Верховній Раді, 17.06.2015, 14:11
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OPORA/publicwhip/issues/94#issuecomment-157961249.

## 

Iurii Lisovskyi
tel/fax: +38 044 286 2670
