### ISSUE TITLE
Translate individual division title that includes MP vote

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#96]
Could we please have the Ukrainian translation for this version of the individual division page title that includes MP vote positions:

> Олег Медуниця voted with the majority (Yes) on the division Поіменне голосування про проект Постанови про Тимчасову президію першої сесії Верховної Ради України восьмого скликання (№1001) - за основу та в цілому

See https://tvfy-ukraine.oaf.org.au/people/rada/Виборчому_округу_№157/Олег_Медуниця/divisions/2014-11-27/20

![screen shot 2015-11-17 at 11 53 02 am](https://cloud.githubusercontent.com/assets/1239550/11199452/cf4b87ea-8d21-11e5-8cd8-aefc17225082.png)

**Comment by lisoffsky** [comment]
Voted with the majority (Yes) on the division - проголосував разом з більшістю (ЗА) по законопроекту...

@orybiy, please confirm

**Comment by henare** [comment]
@lisoffsky @orybiy I think this is quite a bit more complex than @equivalentideas suggests above. I think it's [this that needs translating](https://github.com/OPORA/publicwhip/blob/develop/app/helpers/divisions_helper.rb#L139-L167).

Here's the possible phrases. I'm not sure if we use them all for Ukraine. The italics and link location are also important:

MP was absent:

> [#{persons_name}](#) did not vote on the division #{division_description}

Vote was tied:

> [#{persons_name}](#) voted #{persons_vote} on the division #{division_description}

Different vote outcomes:

> [#{persons_name}](#) voted _with the majority_ (#{persons_vote}) on the division #{division_description}
> [#{persons_name}](#) voted _in the minority_ (#{persons_vote}) on the division #{division_description}

**Comment by orybiy** [comment]
Voted with the majority (Yes) on the division - проголосував/ла разом з більшістю (ЗА): (division_description)

MP was absent: {persons_name} did not vote on the division #{division_description} - {persons_name} відсутній/ня під час: {division_description}

MP was present but did not vote : {persons_name} did not vote on the division #{division_description} - {persons_name} був/була присутній/ня, але не голосував/ла: {division_description}

{persons_name} voted #{persons_vote} on the division #{division_description} - {persons_name} проголосував/ла {persons_vote YES|NO/Abstain}  (ЗА/ПРОТИ/УТРИМАТИСЬ): {division_description)

{persons_name} voted with the majority (#{persons_vote}) on the division #{division_description} - {persons_name} проголосував/ла _разом з більшістю_ {persons_vote}: {division_description}

{persons_name} voted in the minority (#{persons_vote}) on the division #{division_description} - проголосував/ла _разом з меншістю_ {persons_vote}: {division_description}

**Comment by henare** [comment]
@orybiy I think you're saying that the translations need to differ depending on the gender of the deputy, is this correct?

If so, we need to work out another way to say this because the application doesn't currently know the gender of the person. Can someone please suggest an alternative way to say this that doesn't involve modifying the phrase based on the subject's gender?

**Comment by orybiy** [comment]
As I wrote somewhere before, we do not expect to have such  application that knows the gender. So we have to write both variants at the same time, for example:  проголосував/ла
Everything mentioned in my post above can work.

**Comment by equivalentideas** [comment]
Thanks @orybiy I'm working on this now:
- [x] MP was absent: {persons_name} did not vote on the division #{division_description} - {persons_name} відсутній/ня під час: {division_description}
- [x] {persons_name} voted #{persons_vote} on the division #{division_description} - {persons_name} проголосував/ла {persons_vote YES|NO/Abstain} (ЗА/ПРОТИ/УТРИМАТИСЬ): {division_description)
- [x] {persons_name} voted with the majority (#{persons_vote}) on the division #{division_description} - {persons_name} проголосував/ла разом з більшістю {persons_vote}: {division_description}
- [x] {persons_name} voted in the minority (#{persons_vote}) on the division #{division_description} - проголосував/ла разом з меншістю {persons_vote}: {division_description}
- [x] MP was present but did not vote : {persons_name} did not vote on the division #{division_description} - {persons_name} був/була присутній/ня, але не голосував/ла: {division_description}
  **I think are now, this should use the same scenario as the other non-abstain vote types: #{persons_name} voted in the minority (#{persons_vote}) on the division #{division_description}**
