### ISSUE TITLE
Translate 'Електронний протокол засідання ВРУ' hover text to Ukrainian

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#98]
This is helper text for the link to the debate on the Rada’s website:

> Links to debate shown at www.openaustralia.org

See https://tvfy-ukraine.oaf.org.au/divisions/rada/2015-11-13/4589

![screen shot 2015-11-17 at 2 40 21 pm](https://cloud.githubusercontent.com/assets/1239550/11202163/680fc20e-8d39-11e5-90fe-f46b38d7b8da.png)

**Comment by henare** [comment]
Note that this doesn't go to the debate for Ukraine - it goes to the full day's proceedings as that's the most useful link we could add. See https://github.com/openaustralia/ukraine_verkhovna_rada_votes/issues/9

**Comment by orybiy** [comment]
Links to debate shown at www.openaustralia.org - Посилання на стенограму пленарного засідання на сайті ВРУ rada.gov.ua
