### ISSUE TITLE
Translate policy position on vote

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#99]
We need the Ukrainian translation for the text that states the relationship between a policy and a vote, e.g. :

> People who are `<policy>` would have voted `<vote type: yes, no, abstain, or not vote>`

See https://tvfy-ukraine.oaf.org.au/divisions/rada/2014-11-27/20

![screen shot 2015-11-17 at 2 52 51 pm](https://cloud.githubusercontent.com/assets/1239550/11202345/4663a632-8d3b-11e5-92bf-f4c11e63d042.png)

Also we need the translation for the link:

> Add or update related policies

**Comment by lisoffsky** [comment]
People who are -policy- would have voted -vote type: yes, no, abstain, or not vote- -
"Депутати які -policy- також проголосували б -vote type: yes, no, abstain, or not vote-"

Add or update related policies - 
"Додати або оновити пов'язані політики"

(sorry can't get how to paste code)
